### ISSUE TITLE
Updating Plugin Dev documentation about description.md

### ISSUE THREAD

**Issue by dgmccart** [chanzuckerberg/napari-hub#1001]
Issue to track improving the napari hub plugin dev documentation to describe the purpose of description.md and explain where plugin package metadata should be documented.

TODO
- [x] #1022
- [x] Ensure that napari hub CLI docs and dev feedback reflects napari community priorities for metadata locations
- [x] #1023

Assets:

- [Discussion](https://github.com/chanzuckerberg/napari-hub/discussions/627)
- [Current documentation](https://github.com/chanzuckerberg/napari-hub/wiki/Customizing-your-plugin's-listing#description)
- [Plugin Preview Page](https://github.com/chanzuckerberg/napari-hub/wiki/Setting-up-the-napari-hub-Plugin-Preview-Page-for-your-PRs) 
- [napari hub CLI](https://github.com/chanzuckerberg/napari-hub-cli)

**Comment by kandarpksk** [comment]
FYI, this is a recent PR I made of my own accord while exploring plugin creation: https://github.com/napari/docs/pull/143
