### ISSUE TITLE
Review and update doc describing how we source the plugin description info

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#1022]

**Comment by kandarpksk** [comment]
FYI, this is a recent PR I made of my own accord while exploring plugin creation: https://github.com/napari/docs/pull/143#discussion_r1179488353

**Comment by dgmccart** [comment]
Updated made [here](https://github.com/chanzuckerberg/napari-hub/wiki/Customizing-your-plugin's-listing#description).
