### ISSUE TITLE
Backend to return plugin sections data for home page

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#1035]
Create a backend endpoint to return various sections of the homepage consistently.

**Comment by manasaV3** [comment]
Things that need clarity:

- How often do we refresh the sections?
- How do we handle duplicates across the sections? What is the priority for sections?

**Comment by manasaV3** [comment]
API Contract for endpoint: https://docs.google.com/document/d/1Md39pS3v7yP8a7fNb6qfAmFY4arVUjIuJZTi3JVz9hw/edit#

**Comment by manasaV3** [comment]
The endpoint should be API key protected. 
```
curl -X GET --header "X-API-Key: secret-api-key" https://api.napari-hub.org/plugin/home/sections/foo,bar,baz
```
