### ISSUE TITLE
Update Backend Python Version to 3.9

### ISSUE THREAD

**Issue by klai95** [chanzuckerberg/napari-hub#1043]
Reference: https://github.com/chanzuckerberg/napari-hub/blob/main/backend/Dockerfile#L1

We should be updating Python Version to 3.9. data-workflows is already on Python Version 3.9: https://github.com/chanzuckerberg/napari-hub/blob/main/data-workflows/Dockerfile

**Comment by richaagarwal** [comment]
Closing this one, as #1153 is a duplicate
