### ISSUE TITLE
Replace S3 category calls with DynamoDB

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#1057]
## `get_categories_mapping`

- Used for getting mapping for all categories
- Replace with `CategoryModel.get_all_categories(version)`

https://github.com/chanzuckerberg/napari-hub/blob/15ea22a7e9789f42844a5ff2241e9d30d66071eb/backend/api/model.py#L211-L213

## `get_category_mapping`

- Used for getting  a specific category
- Replace with `CategoryModel.get_category(category, version)`

https://github.com/chanzuckerberg/napari-hub/blob/15ea22a7e9789f42844a5ff2241e9d30d66071eb/backend/api/model.py#L215-L217

https://github.com/chanzuckerberg/napari-hub/blob/15ea22a7e9789f42844a5ff2241e9d30d66071eb/backend/preview/preview.py#L60-L62

**Comment by richaagarwal** [comment]
@codemonkey800 I think enabling feature flagging on the back-end would still be very valuable (see https://github.com/chanzuckerberg/napari-hub/issues/811#issuecomment-1502426348) but I'd like to ensure we wrap up migrating the category work sooner than later, so let's not make it a dependency for this work.

**Comment by manasaV3** [comment]
As we will be moving away from the current plugin update workflow triggered by the `/update` endpoint and to use data-workflows. I think it might be more optimal to only update the preview's usage of the categories to dynamo table. 

Also, if the categories have been sufficiently validated while guarded by a feature flag, would this issue be a good opportunity to work on updating all the categories endpoints to serve data from dynamo by default?
