### ISSUE TITLE
Create /plugins/index/all API endpoint

### ISSUE THREAD

**Issue by richaagarwal** [chanzuckerberg/napari-hub#1058]
This endpoint should behave similarly to `/plugins/index` (see https://github.com/chanzuckerberg/napari-hub/issues/950), including being secured by an API key, with a few key differences:

- Return all plugins, not just public ones
- Return plugin `visibility` field
- Do not return activity metrics fields such as `total_installs` and any other ones we may add to `/plugins/index`.

**Comment by richaagarwal** [comment]
@manasaV3 to coordinate or socialize this new endpoint to @bnelson-czi and @seankmartin

**Comment by richaagarwal** [comment]
@manasaV3 Looks like this was released today! Do you want to wait to close until you've synced Ben and Sean?

**Comment by manasaV3** [comment]
I was planning to close this today and have them confirm on https://github.com/chanzuckerberg/napari-hub/issues/1202, that we can go ahead and remove those endpoints. Let me know your thoughts on that. :)

**Comment by richaagarwal** [comment]
Sounds good to me!
