### ISSUE TITLE
Frontend monitoring + alerts in AWS

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#1064]
Currently the only monitoring we have for the frontend are container logs for the frontend server on AWS CloudWatch. We should look into expanding how the frontend is monitored so we get deeper insight into how the application is running and so we can get notified via alerts if anything wrong happens on the frontend.

## Required

- [x] Send browser logs to AWS
- [x] Add alerts for when an error occurs on the server or client

## Nice to have
(not planned for upfront work)

- [ ] Track metrics for server container
- [x] Track web vitals on the browser
- [ ] Create dashboard for displaying:
  - [ ] Container health
  - [x] Error count
  - [x] API request info
  - [x] Web vitals

**Comment by manasaV3** [comment]
Cloudwatch RUM was introduced in aws provider 4.20.0: https://registry.terraform.io/providers/hashicorp/aws/4.20.0/docs/resources/rum_app_monitor

Napari hub's aws provider is currently on 4.18.0. As the dependency for 4.20.0 for aws provider also is terraform 0.13 , we should be able to upgrade the aws provider versioning. Here is the changelog for the version bump: https://github.com/hashicorp/terraform-provider-aws/blob/v4.20.0/CHANGELOG.md

Also, setting up cloudwatch rum has dependency on congnito identity pools for guest access. Linking cognito documentation for terraform here.

**Comment by richaagarwal** [comment]
Moving this back into the "Pending QA & Release" column - we can close it out once we've enabled the alarms again
