### ISSUE TITLE
Clean up older calls for s3 files

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#1130]
### Cleaning up metrics s3 files
- [x] #1148
- [x] Validate maintenance dynamo data to be consistent with s3 data
- [x] #1178
- [x] Validate no calls made to s3 for activity data
- [x] #1179
- [x] #1180

### Cleaning up plugins s3 files
- [x] #1191
- [x] Validate no calls made to s3 for plugin data
- [x] #1192
- [x] #1193

**Comment by manasaV3** [comment]
Relates to https://github.com/chanzuckerberg/napari-hub/issues/845

**Comment by richaagarwal** [comment]
@manasaV3 Linking to this older comment you wrote in case it's helpful to track in this ticket: https://github.com/chanzuckerberg/napari-hub/issues/845#issuecomment-1499710073

**Comment by richaagarwal** [comment]
Removing the epic label so that we can see this in our [sprint board](https://github.com/orgs/chanzuckerberg/projects/12/views/26), but we can still track the parent epic in our [roadmap board](https://github.com/orgs/chanzuckerberg/projects/23) 🚀

**Comment by manasaV3** [comment]
Validation for S3 files are no longer being used other than during the plugin update workflow: 

From the datadog traces [here](https://app.datadoghq.com/apm/traces?query=%40_top_level%3A1%20env%3Astaging%20service%3Aaws.s3%20resource_name%3As3.getobject&cols=service%2Cresource_name%2C%40duration%2C%40http.method%2C%40http.status_code%2C%40_span.count%2C%40_duration.by_service&graphType=span_list&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanType=service-entry&start=1691103790790&end=1691449390790&paused=false) we can see all the `s3.getObject` calls made are as a part of the backend plugin update workflow in staging during a period of 4 days.
