### ISSUE TITLE
Use current plugin installer image for the install instructions

### ISSUE THREAD

**Issue by tlambert03** [chanzuckerberg/napari-hub#114]
#### Description
in the modal dialog that pops up when you click an "install" button, the text says "... paste it where it says “Install by name/url…”, but the image shown is from before napari had the "install by name" option.  That might be a bit confusing?

<img width="613" alt="Untitled" src="https://user-images.githubusercontent.com/1609449/123497545-15412d80-d5fc-11eb-853c-93e87f336ed1.png">

**Comment by justinelarsen** [comment]
Good catch @tlambert03 ! @neuromusic I think this is high priority. Can we prioritize it? cc @liaprins-czi @codemonkey800 @kne42

**Comment by neuromusic** [comment]
+1 @justinelarsen 

thanks @tlambert03 !!

**Comment by neuromusic** [comment]
Here's an updated image.... ![image](https://user-images.githubusercontent.com/1245615/123523401-1c0d8600-d678-11eb-948b-baf304808138.png)

**Comment by justinelarsen** [comment]
Thanks @neuromusic ! This image looks taller than the old one. I wonder if this will make the pop up too tall. Also, having empty space in the installed plugins section may be a little confusing. @liaprins-czi Can you advise?

**Comment by liaprins-czi** [comment]
Hmm that is strange, the image Talley showed in the screenshot is not the same as in the design:
https://www.figma.com/file/pDKU0CdSzpSWGaoXXQVJLz/v0-hub-final-designs?node-id=17%3A220

I will export the images used in the design and add links to them here, so we can be sure to use those ones. Can any of you (@justinelarsen @neuromusic @tlambert03 ) verify that that the Figma design image is the correct version we want to show? I am using a yellow outline to show the area to paste.

**Comment by tlambert03** [comment]
yeah, the figma design looks great

**Comment by neuromusic** [comment]
Woops, you're right @justinelarsen ... I should have reached out to @liaprins-czi instead of snagging a screenshot myself 😬 

And yes @liaprins-czi your original Figma design is perfect. 💯

**Comment by liaprins-czi** [comment]
Okay great, thanks @tlambert03 + @neuromusic ! 

@codemonkey800 Here is a link to exported JPGs of the install screenshots:
https://drive.google.com/drive/folders/14nXkyotEMY5cU4w4M8HVqfiJju048-Ho?usp=sharing

**Comment by justinelarsen** [comment]
Thanks @liaprins-czi ! @codemonkey800 or @kne42 Can you please update before the launch? Thanks!

**Comment by codemonkey800** [comment]
sounds good, I can take a look into this one 😄
