### ISSUE TITLE
Improve E2E Testing

### ISSUE THREAD

**Issue by joshkmartinez** [chanzuckerberg/napari-hub#1147]
The current E2E tests have many opportunities for improvement such as expanding their scope, improving stability, and increasing visibility of their outcomes.

Tasks

- [x] Add tests for firefox and webkit browsers
- [x] Add test retries
- [x] Configure testing to be run on staging, rather than a mock backend
- [x] Send notifications of test failures to slack
- [x] Test staging / prod after deployment

**Comment by richaagarwal** [comment]
@joshkmartinez @codemonkey800 Should we close this one out now that all listed tasks are complete, or did we want to wait until https://github.com/chanzuckerberg/napari-hub/pull/1208 is merged in?
