### ISSUE TITLE
Inconsistency in plugin commit data

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#1164]
We have noticed two issues with the data stored for GitHub commits in Snowflake.

- Repositories of napari plugins are getting classified as repo_type=`"tool"` or `"acquisition"` incorrectly in the table. The expected repo_type for these records is `"plugin"`.  This issue is because some plugin repositories are part of orgs that have been classified as `"tool"` or `"acquisition"`.  The repositories that have been identified to be impacted by this issue are: 
DeepLabCut/napari-deeplabcut, napari/docs, napari/napari-animation, napari/napari-graph, napari/napari-svg, ome/napari-ome-zarr

- Plugin commit data seems to be getting deleted in the snowflake. For example, for the plugin `napari-allencell-segmenter` , there were more records in Snowflake in the past. In the data in staging environment for this plugin, it has records starting from February 2021. These record were written on May 10, 2023. But on checking the snowflake now, it has records only from October 2022. More analysis is need to identify how many plugins are impacted by this issue.

**Comment by bnelson-czi** [comment]
- Fixed the issue where a plugin was being assigned to multiple repo_types. In essence, if it's both a napari plugin and part of GitHub organization related to imaging tools/acquisition, we now prioritize it as `repo_type = 'plugin'`
- I overwrote the entire commits table with new and accurate data. Still unclear why `napari-allencell-segmenter` had this problem when other plugins didn't. At the very least, we can overwrite the table again if we encounter more data discrepancies in the future.
