### ISSUE TITLE
Link to Project site doesn't work

### ISSUE THREAD

**Issue by haesleinhuepf** [chanzuckerberg/napari-hub#1187]
#### Description
The link to Project site is not clickable on some plugins

#### Steps/Code to Reproduce
Navigater to this page:
https://www.napari-hub.org/plugins/napari-workshop-browser

Click here:
![image](https://github.com/chanzuckerberg/napari-hub/assets/12660498/b1373c59-9d2a-4927-a2db-a31344ff975d)

#### Expected Results
I go to the Project page

#### Actual Results
Nothing happens

**Comment by dgmccart** [comment]
For all icons, none of the links in the dropdown menus work, including the project site link

**Comment by richaagarwal** [comment]
@haesleinhuepf thank you for reporting this & @dgmccart thanks for poking at this some more! For me, all the links work, although some require clicking a 2nd time, which is not ideal.

@codemonkey800 could you look into this? If it's a light lift, I think it'd be worth taking on.

**Comment by haesleinhuepf** [comment]
>  For me, all the links work, although some require clicking a 2nd time, which is not ideal.

Maybe this is a browser related issue. I'm working with Chrome on Windows. Clicking on the "Documentation" on [this page](https://www.napari-hub.org/plugins/napari-workshop-browser) does not work in any case.

**Comment by dgmccart** [comment]
I am using Chrome on a Mac and double-clicking doesn't fix the issue for me.

**Comment by richaagarwal** [comment]
Thanks all for the info! I'll have the team look into this and hopefully work on a fix.

**Comment by richaagarwal** [comment]
@codemonkey800 Just a heads up that I'm labeling this a P2/medium priority again given our [bug prioritization definition](https://github.com/chanzuckerberg/napari-hub/wiki/Bug-prioritization). Even though it's a P2, it seemed worth doing an initial investigation into and whether there might be a quick fix available.  I know you haven't been able to reproduce yet but keep us posted on your findings.

**Comment by haesleinhuepf** [comment]
> can still extract the URL and manually navigate to it even if it's not clickable

Do you think this is a workaround common end-users are aware of?

**Comment by richaagarwal** [comment]
> > can still extract the URL and manually navigate to it even if it's not clickable
> 
> Do you think this is a workaround common end-users are aware of?

@haesleinhuepf That's a good point - possibly not, but it is one component of how we prioritize bugs (vs. there being no possible workaround). The exact priority (low or medium) in this case isn't going to change the fact that we are investigating. 

Given where we are with resourcing, in general we are currently only able to commit to taking on high or critical bugs that significantly impair site functionality, though that could change in the future and we appreciate the feedback and bug reports!

**Comment by haesleinhuepf** [comment]
Hi @codemonkey800 ,

it works now. Awesome.

Thanks!

best,
Robert
