### ISSUE TITLE
Fix e2e tests for staging

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#1196]
- Requests for API data fail. this is because we're fetching the plugin data for every plugin on staging. this is very taxing on staging and does not scale well with plugin data
  <img width="650" alt="image" src="https://github.com/chanzuckerberg/napari-hub/assets/2176050/74eae3e8-a694-4c16-b7a1-3a92cc3b4cf5">
- test reports are too long because they test all search results instead of just the first page, making it complex to debug (see video below)
- missing test data for `total_installs`
- selectors matching multiple items. this might be because charles initially tested it on data that didn't have multiple results, so he didn't add code to account for it
  <img width="650" alt="image" src="https://github.com/chanzuckerberg/napari-hub/assets/2176050/d502cd2f-5e03-40c8-8b4d-ebe10ba63808">

## long test report
https://github.com/chanzuckerberg/napari-hub/assets/2176050/cb6222c3-11f4-430c-bd89-29a0946795da

**Comment by richaagarwal** [comment]
@codemonkey800 Is this still in progress or complete?
