### ISSUE TITLE
Secure relevant API endpoints with API keys

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#1201]
Add authorization for endpoints to allow access to specific endpoints.

**Comment by manasaV3** [comment]
Please find considerations for this issue [here](https://docs.google.com/document/d/1qI3HGMS1BP2DBOiBiDyA4oXo0y8TIkKBvbEDyMxWtAE/edit?usp=sharing).

**Comment by richaagarwal** [comment]
Closing this as we won't proceed with this for now due to the considerations in the comment above.
