### ISSUE TITLE
Removal of `/plugins` impacts npe2

### ISSUE THREAD

**Issue by nclack** [chanzuckerberg/napari-hub#1263]
#### Description

The `/plugins` endpoint was removed in (#1212), but `npe2` relies on it (see napari/npe2#313 for details and fix). Functionally the `/plugins` endpoint was moved to `/plugins/index/all`.

However, for already released versions of npe2 use of the hub api to list plugins is broken.

Is it possible to make `/plugins` active again, possibly forwarding to `/plugins/index/all`?

It's not clear to me that anything actually uses the `get_hub_plugins()` function in `npe2` (besides a test). But I think it's a pretty good idea to at least use a deprecation window to double-check.

**Comment by richaagarwal** [comment]
@nclack Thanks for reporting, though I don't believe this is a bug on our end.  We announced the deprecation back in May (see https://github.com/chanzuckerberg/napari-hub/discussions/1065), and recently removed the endpoints.

The publicly available/supported endpoints are listed at https://api.napari-hub.org/.  `/plugins/index/all` is meant for internal usage/ internal users, and is not considered a supported endpoint.
