### ISSUE TITLE
Filter dependencies for plugins

### ISSUE THREAD

**Issue by JacksonMaxfield** [chanzuckerberg/napari-hub#127]
### Primary persona(s)

- [x] Research Biologist
- [x] Imaging Scientist
- [x] Bioimage Analyst

### Job Stories
- **When I** browse for plugins **I want to** know only the dependencies specifically required for installation **so that** I know the minimum requirements / conflicts with my current environment.

### Acceptance Criteria

1. [If I do A, B should happen.]

If I browse napari plugins, only required dependencies should be shown:

![image](https://user-images.githubusercontent.com/17132317/124019226-a2d6a180-d99d-11eb-9606-434eb4e82749.png)

(Nothing with "extra" should be shown, OR it should be separated into an accordian view?)
_([source: aicsimageio napari-hub page](https://napari-hub.org/plugins/napari-aicsimageio))_

**Comment by codemonkey800** [comment]
@JacksonMaxfield check out https://staging.napari-hub.org/plugins/napari-aicsimageio for a preview of your changes. Looks like things are working as expected 😄

**Comment by JacksonMaxfield** [comment]
Woohoo! Thanks @codemonkey800 and @liaprins-czi for the quick review and merge. Any idea when this build will go to prod?
