### ISSUE TITLE
hub is rendering at both www.napari-hub.org and napari-hub.org

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#141]
For SEO purposes, we should make sure that the site only renders at either www.napari-hub.org or napari-hub.org, but not both.

My understanding is that www.napari-hub.org is preferable, as it will better future-proof us if we start to need other subdomains (e.g. api.napari-hub.org for #133)

Whichever we choose, we should ensure that the other has a permanent redirect (e.g. redirect napari-hub.org to www.napari-hub.org)

**Comment by ziyangczi** [comment]
now the bare domain is being redirected via 301 to the www domain
