### ISSUE TITLE
search param isn't added to URL for empty string searches

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#152]
*from June 2020 pre-launch bug bash*

**Created by**: Allen

## Description 

When searching for the empty string, "", the `search` parameter is not added to the URL. I consider this a design issue rather than a functionality issue.

## Info

**Bug source**: *unknown*

**Browser**: *unknown*

**PR**: *none*

**Comment by lauramarcos** [comment]
when searching for empty string, spaces entered in field are showing up as "+++"... dont know if this is desired, if so, please let me know so I can close this one @codemonkey800 ... thank you!
