### ISSUE TITLE
python versions out of order in filters

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#156]
*from June 2020 pre-launch bug bash*

**Created by**: justin

## Description 

I expected the filters to be in order.... 3.7, 3.8, 3.9

## Info

**Bug source**: wide

**Browser**: chrome

**PR**: https://github.com/chanzuckerberg/napari-hub/pull/86

## Attachments

https://dl.airtable.com/.attachments/0921d80bc1ddfbe2882bb28c843c6b63/85b2ecc9/image.png

**Comment by lauramarcos** [comment]
this has been fixed so closing this one. thank you!
