### ISSUE TITLE
filter checkbox hover state off-center

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#160]
*from June 2020 pre-launch bug bash*

**Created by**: Kira Evans

## Description 

the gray circle indicating that you are hovering over the checkbox is misaligned with the checkbox itself

## Info

**Bug source**: *unknown*

**Browser**: *unknown*

**PR**: *none*

## Attachments

https://dl.airtable.com/.attachments/91dd4290861df3f59fd817afff8085a0/e01303e7/ScreenShot2021-06-29at9.02.56PM.png

**Comment by lauramarcos** [comment]
Not happening any more in OS, still pending checking in windows. Thank you!
