### ISSUE TITLE
in-page ToC overlaps footer when window is short enough

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#171]
*from June 2020 pre-launch bug bash*

**Created by**: Lia

## Description 

ToC should go behind footer

## Info

**Bug source**: *unknown*

**Browser**: Chrome + Safari

**PR**: *none*

**Comment by codemonkey800** [comment]
Confirmed with @liaprins-czi that this isn't reproducible anymore, so it likely got fixed by another PR 😄
