### ISSUE TITLE
space between FILTER BY headers/labels are confusing

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#190]
*from June 2020 pre-launch bug bash*

**Created by**: lucy

## Description 

this appears on my ipad but not desktop: the filter by side nav has headers, but i notice the buffer space makes it look funny- there's more space between the header and its corresponding options than the last option of one filter and the next header. Just makes it slightly harder to read....its definitely more traditionally/evenly spaced in desktop

## Info

**Bug source**: *unknown*

**Browser**: *unknown*

**PR**: https://github.com/chanzuckerberg/napari-hub/pull/125

## Attachments

https://dl.airtable.com/.attachments/f9a28502314f6caeea1cf9c680308cdd/f7e7bede/Screenshot2021-06-16at11_43_00AM1.png

**Comment by kne42** [comment]
fixed by #125
