### ISSUE TITLE
pypi search results delayed

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#200]
_reported by @JacksonMaxfield_
_described & discussed on the [napari zulip](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/napari-hub-update-delay/near/245757721)_

#### Description
napari-aicsimageio was updated to 0.3.4 on July 11, however as of today (July 12) it is not showing up on the napari hub.

#### Steps/Code to Reproduce
- see the package on pypi at https://pypi.org/project/napari-aicsimageio/
- see the plugin on the napari hub at https://napari-hub.org/plugins/napari-aicsimageio

#### Expected Results
- the hub should show 0.3.4

#### Actual Results
the hub shows 0.3.3

#### Additional information

presumably, the napari hub has not recognized that the plugin is updated because the pypi search page still lists the version as 0.3.3: https://pypi.org/search/?q=&o=&c=Framework+%3A%3A+napari

however, BiqQuery does seem to have the correct data (h/t @tlambert03 )

``` SQL
SELECT DISTINCT  name, version, home_page, summary
    FROM `bigquery-public-data.pypi.distribution_metadata`
    LEFT JOIN UNNEST(classifiers) cl
    WHERE cl='Framework :: napari'
```
![image](https://user-images.githubusercontent.com/1245615/125386009-6bc69f80-e350-11eb-8a2c-ab70c4712a49.png)

**Comment by neuromusic** [comment]
when we were spec'ing the napari hub, we wanted to make sure that plugins showed up within 5 minutes of being pushed to PyPI and determined that querying BigQuery every 5 minutes didn't meet our requirements. from @ziyangczi 's notes...

> 
> **Pros/Cons:**
> - Pro: Does not require traffic to pypi
> - Con: Requires google project setup. Also we are bound by the update frequency of this dataset and cannot improve scan rate beyond that. It is not documented how frequently it is updated and it can change at any time.
> 
> **Findings:**
> - Still require a backend, can’t solely rely on integrating bigquery API to website due to volume constraint, the bigquery sandbox(basicly free usage) give 1TB of query capacity, however each query would require 1.2 G to run simply to get the names of the plugins. So we cannot run more than hourly update from this method

I can think of at least two possible solutions here that would be fairly straightforward without querying BigQuery more than once per hour....
- when we poll pypi, we no longer consider the version listed at the search page to be the latest... instead, we use that list then check the individual package endpoint to get the latest version
- we could also do the BigQuery search daily or hourly to sync our cache

**Comment by neuromusic** [comment]
note: this package finally showed up, but this should still be fixed for future plugins

**Comment by ziyangczi** [comment]
I am hoping to see another case that this happened so we understand better the frequency, and possibly the reason why this is happening, before taking action to add changes on our end.

**Comment by neuromusic** [comment]
reviewing bugs. curious if you are still seeing this @haesleinhuepf?

**Comment by haesleinhuepf** [comment]
No, I haven't seen that issue for quite a while! Feel free to close this. And big thanks to whoever fixed it ☺️
