### ISSUE TITLE
Timeliness of metadata from GitHub 

### ISSUE THREAD

**Issue by ziyangczi** [chanzuckerberg/napari-hub#22]
With the definition of metadata being laid out here: https://github.com/chanzuckerberg/napari-hub/blob/main/docs/customizing-plugin-listing.md, there are references sourced from GitHub, this becomes an issue across multiple versions, since the GitHub tag may not necessarily correspond to the PyPI release number, for example, a v0.0.1 release may be tagged as 0.0.1 in GitHub, I wonder what people think about managing metadata from github in regards to versions?

**Comment by neuromusic** [comment]
> I wonder what people think about managing metadata from github in regards to versions?

one of the problems/challenges/complaints about PyPI metadata is the way that metadata is pegged to a release & is therefore immutable. so I think that its important for plugin devs to update the description and other metadata immediately without cutting a new release.

I don't think we should worry about mapping between PyPI releases and Github tags & we should simply pull from HEAD of the main/master branch

**Comment by goanpeca** [comment]
>I don't think we should worry about mapping between PyPI releases and Github tags & we should simply pull from HEAD of the main/master branch

That would show data that may not yet be published or accurate I would suggest to use the data from the latest PyPI release 🤔

**Comment by neuromusic** [comment]
>That would show data that may not yet be published or accurate

We have a [very limited set of metadata which we will be pulling directly from Github](
https://github.com/chanzuckerberg/napari-hub/blob/main/docs/customizing-plugin-listing.md#github):

- Summary
- Description
- Authors
- Project Site
- Documentation
- Support
- Report Issues
- Twitter

Everything else will come from PyPI & will reflect the latest release.

**Comment by neuromusic** [comment]
(aside: that reminds me that the table and individual field descriptions do not reflect that all of these fields should pull from Github, even though they were called out in the "Github" section and initial metadata spreadsheet)

**Comment by neuromusic** [comment]
The service that does this best, IMHO, is ReadTheDocs, which lets their developers choose whether they will build & display the "latest" version of the docs (straight from HEAD) or the "stable" version (the last patch release) and specific versions.
