### ISSUE TITLE
Plugin released under one username and repository under organization's name - Error with the GitHub URL on napari hub

### ISSUE THREAD

**Issue by pranathivemuri** [chanzuckerberg/napari-hub#221]
#### Steps/Code to Reproduce

1. Go to https://www.napari-hub.org/plugins/napari-imaging-bb-annotations
2. points to this as the project source https://github.com/pranathivemuri/napari-imaging-bb-annotations
3. Github activity can't be retrieved
4. Project site is incorrect as well

#### Expected Results
<! It should be https://github.com/czbiohub/napari-imaging-bb-annotations
#### Actual Results

![image](https://user-images.githubusercontent.com/10284094/127059628-ae283ba7-e4ec-4acf-b170-b81a0497fb2d.png)

![image](https://user-images.githubusercontent.com/10284094/127059422-76c242d7-b9c6-405e-8d89-3253c9ce1fe6.png)

**Comment by DragaDoncila** [comment]
This one is a result of the Cookiecutter template guessing the github URL to be `https://github.com/github_user/plugin_name`. There's an open PR in cookiecutter to address this behaviour, I'm not sure how much can be done on the hub side

**Comment by pranathivemuri** [comment]
looks like my bad - https://github.com/czbiohub/napari-imaging-bb-annotations/blob/master/setup.py#L46 sorry!
