### ISSUE TITLE
Human readable plugin names

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#237]
### Summary

Offer human-readable plugin names as the primary name of plugins, instead of the Python package name

### Intended Outcome

Naming conventions of Python packages are not very user friendly & we've heard from users that they are confusing. We'll let plugin developers provide human-readable plugin names that aren't subject to the same constraints of PyPI package names.

### How will it work?

Plugin developers will be able to provide human-readable plugin name which will supercede the Python package name if they choose to use it.

### Assets

- PRD (when ready)
- Designs (when ready)
- Tech Spec (when ready)

### Job stories

_napari hub_

- [x]  When I'm viewing a plugin's card, I can read the author's Display Name
- [x]  When I'm viewing a plugin listing, I can read the plugin author's Display Name
- [x] When I search, I get results that match the plugin's Display Name

_Preview Page_

- [x]  When I'm viewing the Preview Page and I don't have a Display Name, I can be reminded that this metadata is missing and see how to add it

**Comment by neuromusic** [comment]
related: https://github.com/napari/napari/issues/3102

**Comment by liaprins-czi** [comment]
Here's a link to the final designs:
https://www.figma.com/file/YhYdskZzQuMQSsnPXEUElW/Human-readable-plugin-names?node-id=24%3A10

**Comment by neuromusic** [comment]
closing in favor of #434 as the primary epic for this work

**Comment by neuromusic** [comment]
frontend work done: https://github.com/chanzuckerberg/napari-hub/issues/434

**Comment by codemonkey800** [comment]
> When I'm viewing a plugin's card, I can read the author's Display Name

<img width="234" alt="image" src="https://user-images.githubusercontent.com/2176050/165858102-d59e541a-4a82-4ab6-a57d-cb4fb9ad6d20.png">

> When I'm viewing a plugin listing, I can read the plugin author's Display Name

<img width="257" alt="image" src="https://user-images.githubusercontent.com/2176050/165858131-a7c2c250-e8a7-4c9d-9b41-bd25194ed06f.png">

> When I search, I get results that match the plugin's Display Name

<img width="806" alt="image" src="https://user-images.githubusercontent.com/2176050/165858192-feeb4aa4-53bd-42f5-a339-1c7331b9483c.png">

> When I'm viewing the Preview Page and I don't have a Display Name, I can be reminded that this metadata is missing and see how to add it

<img width="992" alt="image" src="https://user-images.githubusercontent.com/2176050/165858245-3ccfb3e4-78e8-4ba6-84c6-c6f924ce01db.png">
