### ISSUE TITLE
Shield/pill for plugin devs

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#239]
### Summary

Plugin developers will be able to link to their napari hub listing from their Github repo with a shield.

### Intended outcome

Plugin developers will be able to link to their napari hub listing from their Github repo with a shield.

### How will it work?

We will provide code that a plugin developer can paste into their README that will generate a shield linking back to their napari hub listing.

### Assets
- [Implementation plan](https://docs.google.com/document/d/1Y2KZd5YXZ6JsMlJ1Y9MseMXxP9DC7mdXPztrztDSLpk/edit)

**Comment by liaprins-czi** [comment]
Here’s a link to a doc where I outline the design recommendations for color, style, and logo (with a link to the white version of favicon!)
https://docs.google.com/document/d/1LOB3AhWusGetRTqBxTEGoWuyZ4uY7zHm0Ko4KKyXO4c/edit#
