### ISSUE TITLE
Plugin pages showing template text instead of user docs

### ISSUE THREAD

**Issue by haesleinhuepf** [chanzuckerberg/napari-hub#300]
#### Description
Hi all,

I [find more and more plugins in the hub](https://www.napari-hub.org/?search=The+developer+has+not+yet+provided+a+napari-hub+specific+description.&sort=relevance) with the plugin description:

> The developer has not yet provided a napari-hub specific ddescription

Currently, six out of eight of these plugins have a nice description on GitHub.com . Thus, if the developers would delete [that file](https://github.com/napari/cookiecutter-napari-plugin/blob/master/%7B%7Bcookiecutter.plugin_name%7D%7D/.napari/DESCRIPTION.md) from their plugins, the right description would show up on the hub page. 

#### Steps/Code to Reproduce
Search in the hub for "The developer has not yet provided a napari-hub specific ddescription"

#### Expected Results
The hub should ignore the description.md if it contains the default description and show the content of the readme.md instead.

Furthermore, I don't see why plugin developers should maintain three places for documentation (readme.md, description.md and readthedocs/mkdocs/sphinx). One place is already challenging for many developers, as one can see with all the plugins that have the default readme.md and zero user documentation in the hub. Raising awareness that documentation is important would be nice. 🙂

**Comment by codemonkey800** [comment]
Thanks for the feedback @haesleinhuepf!

@neuromusic @potating-potato I recall we used to source the plugin description from the `README.md` file in the past. but it looks like we're not doing that anymore:

https://github.com/chanzuckerberg/napari-hub/blob/c83e89c8981b02775824e4608078e0ea8f9636f0/backend/utils/github.py#L96-L99

Did we remove this functionality for some reason?

> readthedocs/mkdocs/sphinx

This is a very interesting use case. My impression is that docs hosted on a separate website can be complimentary to the plugin README, where the plugin README would be a light intro to the plugin and how to use it, and the external docs would include detailed information, API references, etc. 

I'm sure you've seen this, but we also have a place for external documentation which could link to readthedocs/mkdocs/sphinx:
![image](https://user-images.githubusercontent.com/2176050/139943632-36e1da84-8f8a-4536-b7b2-fa02db5f69e3.png)

**Comment by haesleinhuepf** [comment]
> I recall we used to source the plugin description from the README.md file in the past. but it looks like we're not doing that anymore

You still are.

**Comment by codemonkey800** [comment]
Somehow I missed the part about deleting the file to have it use the README.md 😭 

I think this is something we have to add to the backend then cc: @potating-potato

**Comment by DragaDoncila** [comment]
This is something we did discuss at some stage but I think got lost in the flurry of work leading up to the napari hub release.

The cookiecutter `.napari/DESCRIPTION.md` contains a bunch of commented out stuff that guides users on filling it out, and then it just has the one sentence "The developer has not yet provided a napari-hub specific description" not commented out.
On the hub side, I thought our logic was going to check for this sentence specifically, and pull the README.md if that's all that was in there.

We should update the backend with this logic.

> Furthermore, I don't see why plugin developers should maintain three places for documentation (readme.md, description.md and readthedocs/mkdocs/sphinx). 

@haesleinhuepf the reason we initially introduced the DESCRIPTION.md file is that many READMEs contain a lot of information about contributing to the repository, running tests, installing dev environments, etc. Our concern was that this could be intimidating for users who really just want to get an overview of how to use the plugin.

We also support linking out to additional documentation where it's relevant e.g. [cellfinder](https://www.napari-hub.org/plugins/cellfinder-napari) links out to their full docs.

You're right that we should be pulling the README.md wherever possible though! This was an oversight on our part.
