### ISSUE TITLE
Preview page building may not behave correctly

### ISSUE THREAD

**Issue by liu-ziyang** [chanzuckerberg/napari-hub#314]
#### Description
1. citation link does not work on preview page
2. License information is only pulled from the main branch of a repo, PRs that update license information is not reflected in the preview page

#### Steps/Code to Reproduce
Add napari preview app to a plugin repo
change license information
run preview action to generate preview page

#### Expected Results
1. the citation link should link to the bottom
2. license change is reflected

#### Actual Results
1. the citation link points to incorrect location 
2. license change is not reflected

**Comment by neuromusic** [comment]
@potating-potato was this resolved?

**Comment by potating-potato** [comment]
both of them are active issues. The license issue is upstream from github and I don't think it will resolve shortly, the citation link may be an easy fix though

**Comment by EricMaxWang** [comment]
Assigning for quick check. Seeing as how old this is. Are we able to close out efforts for #1?
