### ISSUE TITLE
[Desktop] Clicking on License on right side menu is not pointing to correct info in screen

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/napari-hub#364]
#### Description
When clicking on License from right side menu, page does not point to that particular info

#### Steps/Code to Reproduce
1. Go to napari-hub page
2. Look for a plugin including "License" info (https://staging.napari-hub.org/plugins/napari-segment-blobs-and-things-with-membranes)
3. Click on "License" menu on right side
4. Pay attention to info displayed on screen

#### Expected Results
License info should be visible in screen

#### Actual Results
Other info than License is displayed on screen

https://user-images.githubusercontent.com/63799148/146242409-c82ba9bd-90fb-4a41-acc8-27a6f695d327.mov

**Comment by neuromusic** [comment]
ohhh this is interesting... it looks like maybe there's an anchor for the "license" metadata section on the left sidebar that the link is jumping to?

**Comment by codemonkey800** [comment]
> ohhh this is interesting... it looks like maybe there's an anchor for the "license" metadata section on the left sidebar that the link is jumping to?

looks like this is the issue, the anchors are conflicting with the user's markdown headers. One thing we can look into is adding a prefix to either the plugin metadata IDs or the user's header IDs
