### ISSUE TITLE
[Mobile] When tapping on filter, screen zooms in, dropdown does not opened and text selector is displayed when tapping on an option

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/napari-hub#367]
#### Description
When tapping on filter, screen zooms in, dropdown does not opened and text selector is displayed when tapping on an option

#### Steps/Code to Reproduce
1. Tap on Filter
2. Tap on any Filter to open dropdown
3. Pay attention to screen
4. Tap on any option of a filter

#### Expected Results
Screen should maintain its correct size and text selector should not be displayed when selecting a filer type

#### Actual Results
Screen zooms in

https://user-images.githubusercontent.com/63799148/146270169-a54edd63-f4ac-41d4-a4f1-9446169a1a90.mov

**Comment by codemonkey800** [comment]
https://github.com/chanzuckerberg/sci-components/pull/98 should fix this issue. I'll make a PR to upgrade `czifui` to `1.5.4`
