### ISSUE TITLE
`.napari/DESCRIPTION.md` and `CITATION.cff` required when using `napari-hub-preview-action`

### ISSUE THREAD

**Issue by Czaki** [chanzuckerberg/napari-hub#376]
#### Description

When `.napari/DESCRIPTION.md` or`CITATION.cff`is missed then `napari-hub-preview-action` fail with `FileNotFoundError`

https://github.com/4DNucleome/PartSeg/runs/4684547184?check_suite_focus=true#step:3:538

#### Steps/Code to Reproduce

Source of problem is not checking if file exists before try to open it: 

https://github.com/chanzuckerberg/napari-hub/blob/e2ee13d7b75bb9c99ea1f64295d1dd16d935ce68/backend/utils/github.py#L49-L52

The `get_file` function is called here: 

https://github.com/chanzuckerberg/napari-hub/blob/e2ee13d7b75bb9c99ea1f64295d1dd16d935ce68/backend/utils/github.py#L118

and 

https://github.com/chanzuckerberg/napari-hub/blob/e2ee13d7b75bb9c99ea1f64295d1dd16d935ce68/backend/utils/github.py#L123

#### Expected Results

Files should be optional: 
https://github.com/4DNucleome/PartSeg/pull/489#issuecomment-1004374601

#### Actual Results

```
 Traceback (most recent call last):
  File "napari-hub/backend/get_preview.py", line 17, in <module>
    get_plugin_preview(repo_pth, dest_pth, args.local, args.branch)
  File "/home/runner/work/PartSeg/PartSeg/napari-hub/backend/preview/preview.py", line 48, in get_plugin_preview
    github_metadata = get_github_metadata(action_repo_url, branch=branch)
  File "/home/runner/work/PartSeg/PartSeg/napari-hub/backend/utils/github.py", line 118, in get_github_metadata
    description = get_file(repo_url, ".napari/DESCRIPTION.md", branch=branch)
  File "/home/runner/work/PartSeg/PartSeg/napari-hub/backend/utils/github.py", line 51, in get_file
    with open(os.path.join(local_workspace, file)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/PartSeg/PartSeg/.napari/DESCRIPTION.md'
```

@neuromusic

**Comment by neuromusic** [comment]
fixed in #381
