### ISSUE TITLE
i18n is breaking preview page build

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#385]
@codemonkey800 it looks like i18n is breaking the preview page build. 

issue is on this PR: https://github.com/4DNucleome/PartSeg/pull/489

see this step in the build: https://github.com/4DNucleome/PartSeg/runs/4789673543?check_suite_focus=true#step:3:667

cc @czaki

**Comment by Czaki** [comment]
should I close #386?

**Comment by neuromusic** [comment]
:D

no, we'll keep yours.
