### ISSUE TITLE
i18n support is not compatible with next export

### ISSUE THREAD

**Issue by Czaki** [chanzuckerberg/napari-hub#386]
#### Description

When working with the description for napari hub I got `i18n support is not compatible with next export` error. 

It looks related to  #382

```
info  - Copying "static build" directory
Error: i18n support is not compatible with next export. See here for more info on deploying: nextjs.org/docs/deployment
    at /home/runner/work/PartSeg/PartSeg/napari-hub/frontend/node_modules/next/dist/export/index.js:247:19
    at async Span.traceAsyncFn (/home/runner/work/PartSeg/PartSeg/napari-hub/frontend/node_modules/next/dist/trace/trace.js:74:20)
error Command failed with exit code 1.
```

#### Steps/Code to Reproduce

https://github.com/4DNucleome/PartSeg/runs/4789673543?check_suite_focus=true

for PR  https://github.com/4DNucleome/PartSeg/pull/489

#### Expected Results

Expected preview of a new text 

#### Actual Results

Action failed

**Comment by codemonkey800** [comment]
Dang I didn't realize that static exports didn't support the preview page. This wouldn't be a problem if/when we switch to a dedicated frontend server for the preview page, but until then we can just disable i18n for preview pages

**Comment by codemonkey800** [comment]
#387 has been merged. @Czaki could you check if this fixes the preview page build for you please?

**Comment by Czaki** [comment]
Action passed. Looks working.
