### ISSUE TITLE
"Supported Data" is being flagged if not provided on preview page

### ISSUE THREAD

**Issue by DragaDoncila** [chanzuckerberg/napari-hub#393]
#### Description
When building a preview page "Supported Data" is marked as missing, but there's no mention of "Supported Data" in the customize your listing guide, so this would be confusing to users who don't know how to fix this field. 

Conversely if we *do* want this field to be required, we should update the Customize your Listing guide to give instructions on how to add the field, and also add it to the list of fields at the top (which currently still says All fields complete) - @neuromusic flagged that this field is part of the categories work, but shouldn't be "required". 

Feel free to close this issue if the behavior is desired.

#### Example plugin

You can see an example at [this PR](https://github.com/DragaDoncila/default-w-github/pull/1)

![image](https://user-images.githubusercontent.com/17995243/150434033-668f6eae-25b0-4dca-9724-bed036e1fb47.png)

**Comment by codemonkey800** [comment]
This should be fixed by #403 😄
