### ISSUE TITLE
Improve error message for preview page build when plugin does not provide Source Code url

### ISSUE THREAD

**Issue by DragaDoncila** [chanzuckerberg/napari-hub#396]
#### Description
When a plugin does not provide a source code URL, the preview page build fails. See [this run](https://github.com/DragaDoncila/default-wout-github/runs/4888199490?check_suite_focus=true).

I remember a lot of discussion about us not wanting to use the current repo for building preview page, so I think the failing behavior is ok, but we probably want to improve the error message in this case.

#### Expected Results
Meaningful error message e.g. "Plugin default-wout-github did not provide a source code URL. Cannot build preview."

#### Actual Results
```python
Traceback (most recent call last):
  File "napari-hub/backend/get_preview.py", line 17, in <module>
    get_plugin_preview(repo_pth, dest_pth, args.local, args.branch)
  File "/home/runner/work/default-wout-github/default-wout-github/napari-hub/backend/preview/preview.py", line 42, in get_plugin_preview
    meta = parse_meta(wheel_pth)
  File "/home/runner/work/default-wout-github/default-wout-github/napari-hub/backend/preview/preview.py", line 220, in parse_meta
    match = github_pattern.match(proj_site)
TypeError: expected string or bytes-like object
```

**Comment by DragaDoncila** [comment]
So I've realized that we *could* build a preview still here, it just wouldn't include the metadata we pull from GitHub. Do we think this is preferable? Or do we think if there's no GitHub URL we should flag that to the user with an error? @neuromusic @potating-potato @codemonkey800?

**Comment by neuromusic** [comment]
> it just wouldn't include the metadata we pull from GitHub

This is closest to the functionality of the napari hub, so would be my preference.
