### ISSUE TITLE
[Mobile] Image segmentation Region growing Watershed segmentation gets out of screen in plugin page

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/napari-hub#409]
#### Description
Info should fit in screen without getting out of margins

#### Steps/Code to Reproduce
1. Make a search for a plugin including "Image segmentation Region growing Watershed segmentation" info
2. Tap on resulted plugin
3. Pay attention to categories included in plugin page

#### Expected Results
Info should fit in screen without modifying margins

#### Actual Results
Category is larger the screen size making the screen wobbly

https://user-images.githubusercontent.com/63799148/151229496-6303cc3d-fd48-4686-8ade-fdf020946ad6.mov

**Comment by codemonkey800** [comment]
@liaprins-czi is there a specific way you'd like to tackle this in the design? or should we just show a horizontal scroll bar so that the pills can overflow?

**Comment by liaprins-czi** [comment]
Thanks for tagging me @codemonkey800 . Hmm I think the idea to have it be able to side scroll is good temporary fix (would it be able to be just the "pills" zone that side scrolls or would it have to be the full page? ideally not the full page in my mind).

Or we could have the name of the category that isn't a link (so the "Region growing >> Watershed segmentation" part) be appended with a an ellipse "..." for the part that can't fit. Then user can still tap on the "i" icon to geet more info, inclusing the full name. But not sure if this is mroe difficult than the side scrolling of the pill zone, and if so how much harder / would it be worth it, implementation-wise?

**Comment by neuromusic** [comment]
> Then user can still tap on the "i" icon to geet more info, inclusing the full name.

This is a good point... since this issue is restricted to mobile, we may not need the "information rich" pills here and could drop the dimension and parent terms...

So "Workflow step: Image Segmentation > Region Growing > Watershed Segmentation" becomes "Watershed segmentation" on mobile.

**Comment by liaprins-czi** [comment]
That makes sense to me! And if there is ever a primary category name tha tis too long, we can have it condense with the "..." ellipse, or else have the pill zone side scroll

**Comment by codemonkey800** [comment]
Looks like this has been fixed by #443, @lauramarcos can you verify this please?
