### ISSUE TITLE
When clicking on a Category pill from plugin page, previous selection is not mantained

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/napari-hub#411]
#### Description
If a category was selected in homepage, when going to plugin page and clicking on another one, selection from homepage should be maintained

#### Steps/Code to Reproduce
1. Click on Workflow step filter
2. Select any category from the list
3. Click on a plugin in the list
4. Click on a different category pill

#### Expected Results
Category previous selected in homepage should be displayed along with the one clicked on plugin page

#### Actual Results
Category selected homepage is not displayed but only the one selected in plugin page

https://user-images.githubusercontent.com/63799148/151258551-8dd44cc5-54e9-4fcc-b559-df426ac7c2ab.mov

**Comment by codemonkey800** [comment]
That is, should the previous filters be maintained when clicking on a category for the plugin page?

**Comment by neuromusic** [comment]
I can see rationale for both ways when clicking from the plugin page...

1. the current "clear filters" functionality helps the user to pop back out to a broader set of plugins as they explore... e.g. if we turn "author" into a link back to a search/filter, I would expect the site to clear filters
2. keeping the filters as @lauramarcos expected this to work would let the user continue to narrow their search

**Comment by neuromusic** [comment]
(1) feels right to me, but curious what @liaprins-czi 's thoughts are

**Comment by liaprins-czi** [comment]
@neuromusic I agree with "1". I thought we had decided that for categories, if you clicked any of the pills, it overrode any other category settings (clearing them), and applied only the category of the pill you clicked. This is how I would expect it to be. If user wants to combine categories to search through more than one within a given dimension, then they can still do this by using the actual filter mechanism.
