### ISSUE TITLE
User Story: improved category selection

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#420]
### Primary persona(s)

- [x] Research Biologist
- [x] Imaging Scientist
- [x] Bioimage Analyst

### Job Stories
- **When I** select a category, **I want to** see my selection applied immediately **so that** I know that my selection has been applied.

### Acceptance Criteria

1. In the ComplexFilter component, making a selection immediately applies that selection
2. After a selection, the dialog stays open to allow multiple selections to take place

### Resources:

* Relevant component: https://chanzuckerberg.github.io/sci-components/?path=/story/complexfilter--multiple-select

### Context
* Feedback from user @psobolewskiPhD: https://github.com/chanzuckerberg/napari-hub/discussions/299#discussioncomment-2084528

### Notes

slack comment from @liaprins-czi: 
> I have never had the categories blink when I select them, but either way, I see the benefit of the filter applying as soon as the checkbox is selected, if possible. I have been playing with the filters the past few days and it is a little unexpected that it doesn’t do that to me.

**Comment by neuromusic** [comment]
Ah! that explains the "highlight"... still, agreed that it should be more clear how to apply the filter.

**Comment by psobolewskiPhD** [comment]
So, feature request: dark mode? 😉
