### ISSUE TITLE
Filtering reader & writer plugins based on file extension support

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#425]
### Summary
Add support for filtering reader & writer plugins based on which file extension(s) they support.

### Intended outcome
When a user has a specific file type that they need to open (or save), they will be able to find plugins that can read (or write) their file.

### How it will work
The npe2 manifest lets plugin developers explicitly define which file extension(s) reader and writer plugins support. We will use this information to add the relevant filters to the napari hub and make them available through the napari hub API.

### Job stories

_napari hub_

- [x]  When I'm searching for plugins, I can filter by the file extensions that plugins can read so that I can find plugins that will load my data
- [x]  When I'm searching for plugins, I can filter by the file extensions that plugins can write to so that I can find plugins that will let me export my data
- [x]  When I'm viewing a plugin's listing, I can read the list of file extensions that can be loaded with this plugin
- [x]  When I'm viewing a plugin's listing, I can read the list of layers that this plugin can write

_Preview Page_

- [x] When I'm viewing my plugin's preview page, I can see the metadata for file extension and layer support

**Comment by neuromusic** [comment]
closing in favor of #434 as the primary epic for this work

**Comment by codemonkey800** [comment]
> - When I'm searching for plugins, I can filter by the file extensions that plugins can read so that I can find plugins that will load my data

<img width="244" alt="image" src="https://user-images.githubusercontent.com/2176050/165858926-70e25c89-d4b9-4d92-a9ee-55a8f97886c5.png">

> - When I'm searching for plugins, I can filter by the file extensions that plugins can write to so that I can find plugins that will let me export my data

<img width="239" alt="image" src="https://user-images.githubusercontent.com/2176050/165858906-c6fc98e4-6f52-448d-b45e-075f992fbf3e.png">

> - When I'm viewing a plugin's listing, I can read the list of file extensions that can be loaded with this plugin
> - When I'm viewing a plugin's listing, I can read the list of layers that this plugin can write
> - When I'm viewing my plugin's preview page, I can see the metadata for file extension and layer support

<img width="254" alt="image" src="https://user-images.githubusercontent.com/2176050/165858874-c9a330c7-09e2-44c9-ace8-8a5645c4ba1c.png">
