### ISSUE TITLE
add support for npe2-enabled features

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#434]
### Summary
We will add support on the napari hub for npe2, inspecting plugins for high priority metadata, presenting the metadata on plugin pages, letting users filter by the plugin metadata, and providing the metadata to napari through the napari hub API.

### Outcome
Users will be able to see human-readable plugin names, filter by plugin type, and filter by file extensions that are supported for reading and writing. napari developers will have access to this metadata through the napari hub API. napari plugin developers will be able to preview this metadata on the Plugin Preview Page.

### How will it work
When new plugins are detected on PyPI, on the backend we will need to download the Python package and inspect the npe2 manifest file for relevant metadata. For legacy plugins, we will attempt to infer this information using the logic in `npe2 convert`

### Assets

- [PRD](https://czi.quip.com/FfcxAlZaUikg/PRD-Add-Support-for-npe2)
- [Designs](https://www.figma.com/file/QjAsUZxg1oauQbMBwOlPIv/npe2?node-id=2%3A571)
- [Tech Spec](https://docs.google.com/document/d/1JWm-71Ak6T85pEbO5g9EOJgm-PMR9LLzLwgqG1vpLL4/edit?usp=sharing)

### Stories

- [x] https://github.com/chanzuckerberg/napari-hub/issues/237
- [x] #467
- [x] https://github.com/chanzuckerberg/napari-hub/issues/425
- [x] #468

**Comment by codemonkey800** [comment]
@lauramarcos to QA the following functionality:

1. Test new npe2 filters on search page: https://staging.napari-hub.org
    <img width="274" alt="image" src="https://user-images.githubusercontent.com/2176050/173941341-ab8de9f1-3d62-4168-8f14-bc790203c3da.png">
2. Test PyPi link on plugin page:
    <img width="291" alt="image" src="https://user-images.githubusercontent.com/2176050/173941580-c7c47c30-0f5f-48ba-8688-6f752d9b1759.png">
3. Verify plugin metadata matches what's is being filtered:
    <img width="233" alt="image" src="https://user-images.githubusercontent.com/2176050/173941742-dc75ce2b-e40e-425b-b3ba-b391d2dc336c.png">
