### ISSUE TITLE
"Image Segmentation" should be "Image segmentation"

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#437]
#### Description
For pills and filters, "Image Segmentation" is in Title Casing when it should be Sentence casing

#### Expected Results
Category should be "Image segmentation" (Sentence casing)

#### Actual Results
<img width="601" alt="image" src="https://user-images.githubusercontent.com/1245615/157160912-d04e3f35-d9a5-413a-9c7c-e3b30f7648b9.png">

**Comment by klai95** [comment]
PR for issue: https://github.com/chanzuckerberg/napari-hub/pull/1038
