### ISSUE TITLE
Filter plugins based on Plugin Type

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#467]
#### Job stories

_napari hub_

- [x]  When I'm searching for plugins, I can filter by Plugin Type so that I can find plugins that offer certain functionality
- [x]  When I'm viewing a plugins card, I can read the Plugin Type so that I can better understand what the plugin does
- [x]  When I'm viewing a plugin listing, I can read the Plugin Type

_Preview Page_

- [x] When I'm viewing the Preview Page, I can see my Plugin Type in the metadata

**Comment by codemonkey800** [comment]
> - When I'm searching for plugins, I can filter by Plugin Type so that I can find plugins that offer certain functionality

<img width="300" src="https://user-images.githubusercontent.com/2176050/165858502-b9e4b15c-3afa-4724-a72f-80169280ab0c.png">

> - When I'm viewing a plugin listing, I can read the Plugin Type
> - When I'm viewing the Preview Page, I can see my Plugin Type in the metadata

<img width="300" src="https://user-images.githubusercontent.com/2176050/165858541-e7e6c948-bd5b-4aa5-9c2b-66878dca1e12.png">

**Comment by codemonkey800** [comment]
> When I'm viewing a plugins card, I can read the Plugin Type so that I can better understand what the plugin does

Just realized I missed this lol I'll make another PR to add it

**Comment by codemonkey800** [comment]
> When I'm viewing a plugins card, I can read the Plugin Type so that I can better understand what the plugin does

![image](https://user-images.githubusercontent.com/2176050/165867415-9cbeff7d-c774-4f79-82d0-7de217ce4f81.png)
