### ISSUE TITLE
User Story: Plugin page metadata links

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#476]
### Primary persona(s)

- [x] Research Biologist
- [x] Imaging Scientist
- [x] Bioimage Analyst

### Job Stories
- **When I** view a plugin page, **I want to** click through the metadata to it can open the search page with the metadata already set in the search filters **so that** I can see other plugins that share this metadata.

### Acceptance Criteria

1. Metadata on the plugin page appears as a link if there is an associated search page filter.
2. Clicking on metadata will take me to the search page with the metadata value set in its associated search filter.

### Notes

Slack thread:

> - turn all metadata on plugin pages that have filters on the search page into clickable links w/ filter auto-populated
>   - _Could just have all clickable metadata on plugin page have underlines to indidcate it is a link + a HTML tooltip like “Show all plugins requiring Python 3.7” (not sure if that is the best phrasing to communicate the intent of that filter, though…)_

**Comment by codemonkey800** [comment]
@lauramarcos for QA: 

1. Verify clicking on metadata will open home page with search parameters. For example, license will open `license=oss`:

    <img width="113" alt="image" src="https://user-images.githubusercontent.com/2176050/168877857-1088f193-8200-4912-a510-002f863e95a9.png">

    here's an example of a plugin with a lot of metadata links: https://staging.napari-hub.org/plugins/vessel-express-napari 

2. Verify authors filter works:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/2176050/168889513-fb8dba5b-2ca9-4a9c-b84b-085a1de77906.png">

**Comment by lauramarcos** [comment]
@codemonkey800 Already tested and working as expected in staging. Thank you!
