### ISSUE TITLE
Wrong date format in preview comment

### ISSUE THREAD

**Issue by Czaki** [chanzuckerberg/napari-hub#491]
#### Description

Currently `napari-hub` uses the American date format (MM/DD/YYYY), but many regions use (DD/MM/YYYY), so, many users may be confused. I think that it will be nice to change to YYYY/MM/DD date format will produce	a more readable comment. 

I also would love to see information about the timezone. 

Instead of
> Preview page for your plugin is ready here:
[preview.napari-hub.org/4DNucleome/PartSeg/622](https://preview.napari-hub.org/4DNucleome/PartSeg/622)
Updated at: 05/08/2022 , 17:24:37 

I would like to see:

> Preview page for your plugin is ready here:
[preview.napari-hub.org/4DNucleome/PartSeg/622](https://preview.napari-hub.org/4DNucleome/PartSeg/622)
Updated at: 2022/05/08 , 17:24:37 UTC

**Comment by potating-potato** [comment]
cc @neuromusic for tracking
