### ISSUE TITLE
P1 - Setup recurring updates / reindexing

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#508]

**Comment by neuromusic** [comment]
@richaagarwal this was a task under #435... can we safely close it?

**Comment by richaagarwal** [comment]
@neuromusic Yes, given the MVP implementation we moved forward with, we are always fetching directly from https://github.com/chanzuckerberg/napari-hub-collections, so setting up recurring updates would not be needed. Closing!
