### ISSUE TITLE
P2 - Cache images for collections

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#509]

**Comment by neuromusic** [comment]
@richaagarwal this was also a task under #435... can we safely close it?

**Comment by richaagarwal** [comment]
@neuromusic It depends on what the criteria for this was, but we do utilize our CDN for collections pages (with a TTL of 5 minutes).  We could probably open up a new ticket if we wanted to further optimize our caching, so I'm happy to close if you are!
