### ISSUE TITLE
option to hide from napari hub not in FAQ

### ISSUE THREAD

**Issue by kevinyamauchi** [chanzuckerberg/napari-hub#514]
#### Description
Hello everyone! I have a very early stage plugin that I do not want to be searchable on the napari hub (yet). I checked the FAQ and it currently says to email the team or raise an issue to "hide" your plugin. However, after speaking with @DragaDoncila , I learned that the config.yml can be used to hide a plugin from the napari-hub search. I think this should be the recommended option in the FAQ.

Thanks!

#### Steps/Code to Reproduce
Visit https://www.napari-hub.org/faq and open the "How do I remove my plugin from the napari hub?" section.

#### Expected Results
I think it would be nice if there was a link to the [relevant section in the config docs](https://github.com/chanzuckerberg/napari-hub/blob/main/docs/customizing-plugin-listing.md#visibility)

#### Actual Results
The FAQ recommends to email the team or raise an issue

![Screenshot 2022-06-01 at 11 07 30](https://user-images.githubusercontent.com/1120672/171369158-3c737874-ab02-473b-b995-2dc72bdd61eb.png)

**Comment by neuromusic** [comment]
ooooo good catch @kevinyamauchi .... the FAQ is indeed out of date

**Comment by richaagarwal** [comment]
Let's update this section to link to these instructions - https://github.com/chanzuckerberg/napari-hub/wiki/Customizing-your-plugin's-listing#visibility - so we don't have to duplicate info in two places.  That wiki doc will be updated soon after @DragaDoncila does some work on deprecating config.yml (and thus impacting visibility options), but if we simply link to that page in the FAQ, then that wouldn't block this work. 

I'll open up a PR shortly :)
