### ISSUE TITLE
Improved author splitting

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#528]
### Who its for

Users when they are searching by author

### Problem it solves

Currently, we populate the Authors filter assigning the PyPI author as a single author, even though many plugin developers populate this string with a list of authors separated by commas, ampersands, "and", and Oxford commas.

This limits the value of the Author filter since it isn't very reliable (e.g. the filter for "Nicholas Sofroniew" misses plugins where Nick is one of many authors)

### How it should work

1. If plugin author information is sourced from PyPI, we should split the author string according to common separators (e.g. `,`, `;`, `&`, and `and`) and assign the results as individual authors to the plugin.
1. If plugin author information is sourced from `.napari-hub/config.yml`, we should use the individual author entries

**Comment by lgan-czi** [comment]
Done with #592!
