### ISSUE TITLE
Source author information from CITATION.cff

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#529]
### Who its for

Plugin developers who have defined a `CITATION.cff` file

### Problem it solves

If the plugin developer has defined a `CITATION.cff` file, this file has author information present, which we should source for author information.

### How it will work

1. If we can find a `CITATION.cff` file, then we override the PyPI author information with the author info therein
2. If the plugin author has defined a `CITATION.cff` file AND listed authors in `.napari-hub/config.yml`, then we source from the config file (which always overrides to ensure customizability)

**Comment by lgan-czi** [comment]
Implemented in #594!
