### ISSUE TITLE
Some plugins with valid `npe2` metadata are missing this metadata on the hub

### ISSUE THREAD

**Issue by DragaDoncila** [chanzuckerberg/napari-hub#568]
#### Description
The current approach for finding `npe2` metadata requires installing the plugin into the container environment. This has worked for a large majority of plugins (both `npe2` and `npe1`), but is not guaranteed to work for all plugins, even native `npe2` ones.

We should:
- [ ] Investigate *why* plugins with no metadata are failing to install/why we're failing to discover the manifest
- [ ] Attempt to address any errors that could trivially be solved with more careful setup of the Docker image
- [ ] Add a backup method for discovering manifests that relies on downloading the package distribution from PyPI and inspecting its metadata to find `napari.yaml`

#### Steps/Code to Reproduce
As an example, see [morphometrics](https://staging.napari-hub.org/plugins/morphometrics) which has no `npe2` metadata, [but is a native `npe2` plugin](https://github.com/kevinyamauchi/morphometrics/tree/main/src/morphometrics)

#### Expected Results
All **native npe2 plugins** should have their `napari.yaml` available at the `/manifest/plugin` endpoint, and visible on the napari hub.

**Comment by richaagarwal** [comment]
@DragaDoncila @manasaV3 Do we have an idea of how many plugins this is impacting?

**Comment by DragaDoncila** [comment]
@richaagarwal I would be very surprised if this issue is still relevant after the updated manifest building logic we introduced late last year. Certainly the linked plugin, `morphometrics` is showing manifest metadata correctly. 

It used to be that the easiest way to check was to hit https://api.napari-hub.org/plugins/index and CTRL+F for `"plugin_types": []` - only plugins for which we have no manifest metadata should have an empty `plugin_types` list. However, I assume the recent API deprecations/changes mean this endpoint is no longer useful, because I just hit it, and 47 plugins have an empty `plugin_types` list - yet each plugin I check from this list has correct metadata on the hub. 

Not sure what the best way is currently to check what plugins we're failing to find manifest metadata for, but I do think this issue can probably be closed off the back of #641, #645, etc. Would be nice to confirm though.

**Comment by manasaV3** [comment]
[This gist](https://gist.github.com/manasaV3/40c31a2870dd55e2a1cdbcaf42a42a38) contains a list of the manifest data that have error messages in them. 

Of the 76 records, 60 of them contain an error message of type `"<plugin name> does not have version <version>"`.  I believe this error originates from [this step of npe2 processing](https://github.com/napari/npe2/blob/80ca5feb501dd25d36ecf1313f94d80366d25b8e/src/npe2/_inspection/_fetch.py#L322). 

For the few plugins that I manually checked the data from pypi, they had data for the specified "version" in the "release" section.  Example: [napari-bud-cell-segmenter version 0.1.4](https://pypi.org/pypi/napari-bud-cell-segmenter/json).  

But the [staging env](https://api.staging.napari-hub.org/manifest/napari-bud-cell-segmenter) was able to fetch the manifest data for the same plugin version.

**Comment by manasaV3** [comment]
Manifest that have `"<plugin name> does not have version <version>"` have been reprocessed.
