### ISSUE TITLE
Add tests for parsing `npe2` manifest

### ISSUE THREAD

**Issue by DragaDoncila** [chanzuckerberg/napari-hub#569]
### Summary
To avoid the `npe2` dependency in the backend and in the interest of merging for release, we had to get rid of some of the tests written for parsing the manifest into its various frontend components. We need to add these tests back in, relying on parsing with `yaml` rather than the `npe2` library.

### Intended Outcome
Better coverage of the manifest parsing logic into frontend attributes.

**Comment by richaagarwal** [comment]
@DragaDoncila @manasaV3 Curious if this is still relevant

**Comment by DragaDoncila** [comment]
@richaagarwal - unlikely. The `parse_manifest` function I'm referring to seems to only be used in the preview page now (not sure how we're actually getting the manifest metadata in there now). Since we'll be deprecating preview page I think we can safely close this.
