### ISSUE TITLE
Search by author (by clicking on name) doesn't show all results

### ISSUE THREAD

**Issue by haesleinhuepf** [chanzuckerberg/napari-hub#580]
#### Description
Search by author by entering their name delivers different results compared to clicking their name.

Related issue: #433 

#### Steps/Code to Reproduce

Go to the napari hub and search for "talley lambert". This will show 11 plugins:

![image](https://user-images.githubusercontent.com/12660498/174924531-a409e819-423d-489f-90d3-b51d3eb05b40.png)

Then, click on the first plugin and on the plugin page, click on the author `Talley Lambert` and this will give you 6 plugins:
 
![image](https://user-images.githubusercontent.com/12660498/174924615-470542b3-2cb4-46e3-bcb5-8b23986b7c7b.png)

#### Expected Results

Both searches should result in the same list of plugins. I presume the issue is that the second search checks if the author is equal to some text, but it should check if some text is in the author-meta-data-entry.

**Comment by haesleinhuepf** [comment]
The list of authors in the author-search could also be improved by splitting the authors in case there are multiple authors:

![image](https://user-images.githubusercontent.com/12660498/174928139-2d6670e3-ed4d-4df7-b769-cfeab44e9f4c.png)

**Comment by neuromusic** [comment]
thanks @haesleinhuepf !!! this has been improved with #528 :D
