### ISSUE TITLE
exclude napari-tomoslice and napari-subboxer

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#582]
Add 2 plugins to exclusion list, at the request of the plugin owner:

- [ ] napari-tomoslice
- [ ] napari-subboxer

**Comment by klai95** [comment]
@neuromusic Just to clarify, what `visibility` value will be set to `napari-tomoslice` and `napari-subboxer` respectively? Right now, there are three distinct values in `excluded_plugins.json`: `hidden`, `disabled`, `invalid`

**Comment by potating-potato** [comment]
hidden: they won't show up in a search on the main page but will still have a plugin page
disabled: won't show up completely
invalid: the plugin data cannot be processed and is therefore excluded by the hub

**Comment by neuromusic** [comment]
thx @potating-potato 

@klai95: we want `disabled` here

**Comment by neuromusic** [comment]
hey @klai95, it looks like these have been disabled... can you confirm and close out this issue?

**Comment by klai95** [comment]
> hey @klai95, it looks like these have been disabled... can you confirm and close out this issue?

@neuromusic Where are you seeing that `napari-tomoslice` and `napari-subboxer` have been disabled? `excluded_plugins.json` on S3 currently do not have these plugins

**Comment by neuromusic** [comment]
@klai95 they aren't on the hub anymore.

perhaps @alisterburt got tired of waiting and pulled them down by another means :D

**Comment by klai95** [comment]
> @klai95 they aren't on the hub anymore.
> 
> perhaps @alisterburt got tired of waiting and pulled them down by another means :D

@neuromusic From my conversation with @DragaDoncila, it seems like the process should be done by the plugins themselves. Since it seems like the two plugins aren't on the hub anymore, can I go ahead and close the issue?
