### ISSUE TITLE
TASK: open PRs to migrate select plugins to using `.napari-hub/config.yml`

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#593]
When #528 lands, the following plugins will have their author fields erroneously split:

- [x] ~https://www.napari-hub.org/plugins/misic-napari by `S. Panigrahi & L. Espinosa, IAM, LCB`~
- [ ] https://www.napari-hub.org/plugins/napari-omero by `The Open Microscopy and napari teams`
- [ ] https://www.napari-hub.org/plugins/recOrder-napari by `Computational Microscopy Platform, CZ Biohub`

These plugins will be able to correct their author information by either (a) adding their author info to `.napari-hub/config.yml` file or (b) adding a CITATION.cff file (once #529 is implemented)

Before we launch #528 to production, we should reach out to these plugin authors w/ PRs that ensure their author info correctly appears on their plugin.

**Comment by neuromusic** [comment]
can't find source code for `misic-napari`

**Comment by richaagarwal** [comment]
@neuromusic I'm assuming this already happened or is no longer needed?
