### ISSUE TITLE
comma-separated authors in plugin cards

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#597]
Once #592 lands, we will have more plugins that are "true" multi-author... however, for plugins with large numbers of authors the card on the search page is now looking somewhat bulky (see below).

![image](https://user-images.githubusercontent.com/1245615/177616093-a9d0c26d-35b5-41cb-8042-bf21366edc57.png)

based on slack convo w/ @liaprins-czi, the intended behavior here is to have authors on the search cards in a single comma-separated string

**Comment by potating-potato** [comment]
@neuromusic should we land frontend changes in the same PR? if so I would delay merging of the current PR

**Comment by neuromusic** [comment]
it should be a pretty straightforward fix, replacing the `<ul>` with comma-separated values: https://github.com/chanzuckerberg/napari-hub/blob/23fcddde78453a4c0b894c1d6447a7265336f2da/frontend/src/components/SearchPage/PluginSearchResult.tsx#L269

if not too much of a lift, would love to land it with #592

**Comment by neuromusic** [comment]
fixed in #592
