### ISSUE TITLE
Improve data validation

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#601]
We had an issue on the hub recently that caused the frontend to break when interacting with a feature that had broken data:

https://github.com/chanzuckerberg/napari-hub/pull/600

We should do some more data validation maybe in both the frontend and backend to ensure things like this don't happen. Would also be nice to have some monitoring to alert us when users encounter exceptions like this so we get alerted earlier if a user encounters it first.

**Comment by klai95** [comment]
I will set up some time with @codemonkey800 to talk about how frontend and backend should handle data validation.

**Comment by klai95** [comment]
Data Validation on Backend:
- Filter out data where empty author names are empty (s3 and frontend won't see this data)
- Make sure utils.py:get_attribute(...) has correct default data structure for each attribute

**Comment by richaagarwal** [comment]
@klai95 @codemonkey800 Do you think it would make sense to consider other fields when filtering out data - for instance what happens if there are no python versions, or the plugin name is missing?

**Comment by klai95** [comment]
The action item `Filter out data where empty author names are empty (s3 and frontend won't see this data)` has already been addressed, and therefore would not be captured in https://github.com/chanzuckerberg/napari-hub/pull/636. @richaagarwal

**Comment by klai95** [comment]
Update: https://github.com/chanzuckerberg/napari-hub/pull/636 has been merged
