### ISSUE TITLE
hub-updates zulip stream is gone

### ISSUE THREAD

**Issue by haesleinhuepf** [chanzuckerberg/napari-hub#603]
#### Description
The napari-hub bot notifying for new plugin releases appears gone from the zulip chat. is this intentional?

#### Steps/Code to Reproduce
Go to napari.zulipchat.com and search the stream "hub-updates':

![image](https://user-images.githubusercontent.com/12660498/178215307-7a208343-f724-44fd-a790-1bec40374797.png)

**Comment by haesleinhuepf** [comment]
Note: I can still see it on my smartphone zulip/app. There are just no recent posts (despite there were plugin releases during the weekend)

**Comment by lgan-czi** [comment]
Hi @haesleinhuepf! This looks to be related to issue #598. We call the Zulip bot whenever we update our backend, and since that's broken due to a change with pypi, the Zulip bot is broken too.

**Comment by richaagarwal** [comment]
This has been resolved by https://github.com/chanzuckerberg/napari-hub/pull/605 and it looks like updates are back!

**Comment by haesleinhuepf** [comment]
Thanks @richaagarwal and @lgan-czi 🌞
