### ISSUE TITLE
Update `plugins` lambda and its triggers to remove chance of infinite loop when fetching `npe2` data

### ISSUE THREAD

**Issue by DragaDoncila** [chanzuckerberg/napari-hub#620]
### Summary
This issue captures the work required to complete TODOs 1 and 2 in #587. This work item is composed of two subtasks:

1. Disable any retry mechanism for failed manifest discovery
2. Update `plugins` lambda trigger to remove chance of file changes retriggering the same lambda

**Rationale**: we think it unlikely that discovery failures would be fixed on a retry, and thus a retry mechanism would be useful only in the case where we failed due to an external reason e.g. PyPI was temporarily down and we couldn't download the package. We can consider implementing a retry mechanism if monitoring reveals a need for it.

### Intended Outcome
Plugins lambda can update successfully built manifest files for new plugins without the potential for an infinite loop.

### How will it work?

Disabling the retry mechanism will involve removing the `failure` lambda entirely and ensuring the `plugins` lambda doesn't error and is not configured for asynchronous retries. 

We still need to decide how to update the triggering mechanism e.g.:

1. Keep the file creation trigger for the lambda, but rather than relying on `process_count` in some plugin's `{plugin}.{version}-manifest.json`, we write a separate (could be blank) file e.g. `trigger.json` to serve as a trigger for the `plugins` lambda. Lambda proceeds as normal discovering manifest. If discovery is successful, lambda writes **correct** manifest to `{plugin}.{version}-manifest.json` and deletes `trigger.json`. If discovery is unsuccessful, `{plugin}.{version}-manifest.json` is **not written** at all (but trigger file is updated with error message?).
2. Completely remove s3 file creation as a trigger for the `plugins` lambda and instead invoke it directly in the backend cache updating methods. In **very rough** pseudocode terms, in `backend/api/model/build_manifest_metadata`:

```python
if "{plugin}/{version}-manifest.json" not in cache and "{plugin}-{version}" not in failed_manifests:
    # we'd want to do some check that the lambda isn't already in action?
    boto3_client.invoke_async(FunctionName='plugins', InvokeArgs='plugin, version')
```

Then, in `plugins/get_plugin_manifest/generate_manifest`:

```python
try:
    manifest = build_manifest(plugin, version)
    if manifest:
        s3.put(manifest, '{plugin}.{version}-manifest.json')
     else:
        update_failed_manifests(plugin, version)
except Exception as e:
        update_failed_manifests(plugin, version)
```

**Comment by richaagarwal** [comment]
@DragaDoncila Is this currently in progress?

**Comment by DragaDoncila** [comment]
@richaagarwal not quite - I'll first work on updating the `plugins` lambda logic - this will be up next after that.

**Comment by richaagarwal** [comment]
@DragaDoncila Sounds good! Do you mean your work in this ticket - https://github.com/chanzuckerberg/napari-hub/issues/621 - or is there another one?

**Comment by DragaDoncila** [comment]
@richaagarwal yep, #621 is up next - I want to update the logic and test independently before we trigger it from the backend update method so that we can get a sense of how long it takes per plugin and iron out bugs

**Comment by DragaDoncila** [comment]
After further discussion on the proposed tech spec we've decided to go with Option 2 - remove the file creation trigger completely and instead invoke the `plugins` lambda directly from the backend after first checking that a manifest file does not already exist for the given plugin + version. More detail is in the [tech spec](https://docs.google.com/document/d/1g36PzXafm1vfbWSW2w4-0rX-xO5rv4rBo27e0_dSE1s/edit?usp=sharing)

**Comment by DragaDoncila** [comment]
@richaagarwal yep, will make those changes. I'm reviewing some of those docs now

**Comment by richaagarwal** [comment]
@DragaDoncila I was thinking we could close this, but it might be good to leave open until we update the documentation (see my last comment: https://github.com/chanzuckerberg/napari-hub/issues/620#issuecomment-1269186527). Let me know if you have any questions about that!

**Comment by DragaDoncila** [comment]
@richaagarwal happy to leave open. Preview page & doc updates are on my list for this week.
