### ISSUE TITLE
drop support for conda channel

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#630]
Per the discussion in https://github.com/chanzuckerberg/napari-hub/discussions/627, we will drop support for specifying conda channels in the napari hub config file.

- [ ] Revert #495 

Then, verify the outcomes:
- We have dropped the `conda` key from API endpoint
- We have stopped ingesting conda fields from `.napari[-hub]/config.yml`

**Comment by richaagarwal** [comment]
@neuromusic Should we also update https://github.com/chanzuckerberg/napari-hub/wiki/Customizing-your-plugin's-listing? Is there any other documentation we need to update?

**Comment by neuromusic** [comment]
good call. done.

**Comment by richaagarwal** [comment]
@neuromusic Just to clarify, there's not a need to clean up existing/historical data here, right? (If so, I can open up a follow-up issue for that if it's important)

**Comment by neuromusic** [comment]
@richaagarwal I don't believe so. this was a barely-communicated feature that I'm pretty sure was unused.
