### ISSUE TITLE
Open PRs onto plugins using the "links" field in , migrating them to use Python core metadata fields for URLs

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#632]
- [ ] https://github.com/AllenCell/napari-allencell-segmenter
  - [ ] https://github.com/jo-mueller/napari-stl-exporter
  - [ ] https://github.com/DragaDoncila/example-plugin
  - [ ] https://github.com/SuperElastix/elastix_napari

**Comment by richaagarwal** [comment]
This will be superseded by the work that @DragaDoncila is doing (captured in https://docs.google.com/document/d/1XNf0KOpJqj1Tzyu9u6KZRdkBTP7m6xSRLExJ6KPhMfM/edit#heading=h.zi22evmfyjbu), so I am closing it here.
