### ISSUE TITLE
Migrate Napari Hub Service(s) From Current AWS Region 

### ISSUE THREAD

**Issue by klai95** [chanzuckerberg/napari-hub#671]
### Summary
Per the incident: https://czi-sci.slack.com/archives/C56QRGLRJ/p1664387467312159, the napari hub website was completely down for roughly 1 hour. 

### Intended Outcome
In order to mitigate this issue, it would make sense to migrate at least some of the napari hub services away from AWS region `US-WEST-2`, so that we can diversity where our services are hosted, and avoid napari hub website being completely down and heavily dependent on said AWS region. This incident may have been 1 hour, but we don't know if there would one in the future that takes longer in time, so this action item is an effort to tackle the issue.

**Comment by manasaV3** [comment]
There is no guarantee for any specific region to not go down completely. So, moving to another region doesn't provide a guarantee of 100% uptime. So,  this might not be the best solution for this problem.
