### ISSUE TITLE
Use datadog for frontend logging

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#682]
Right now any logs from the server side of the hub frontend go into AWS CloudWatch. The UI is cumbersome to use and hard to find logs in a centralized place per environment since logs are organized by container ID.

Any logs from the client side are lost completely since we don't do any tracking.

We should use the [datadog browser logging library](https://docs.datadoghq.com/logs/log_collection/javascript) to capture these logs so that we can monitor these logs.

**Comment by manasaV3** [comment]
Potential AWS cloudwatch counterpart: https://www.npmjs.com/package/aws-cloudwatch-log-browser
