### ISSUE TITLE
Filter plugin installs data

### ISSUE THREAD

**Issue by klai95** [chanzuckerberg/napari-hub#685]
For the `/activity/<plugin>` endpoint, we should filter installs data to the past _n_ months, where _n_ can be specified by the frontend, but otherwise defaults to 12. Additionally, the current month's data is not returned, so the data would always end at the previous month (e.g. in October 2022, we would return available data for October 2021 - September 2022).

### Additional notes
Currently on staging, the data is bunched together as the frontend is not set up to handle more than 12 data points:

<img width="1138" alt="Screen Shot 2022-10-06 at 4 17 03 PM" src="https://user-images.githubusercontent.com/70177777/194420263-30e8dabf-333c-4239-aed5-6e18cdca3724.png">

**Comment by klai95** [comment]
@manasaV3 @codemonkey800 and me have just discussed the following points and we hope to get feedback from @richaagarwal about them:

Ensure frontend has more granular control and building an api that is more extensible; moreover, we are going to set a limit as a param to avoid malicious users from hitting our endpoints too many times, and also set up from and to parameters so users can choose to see which time frame of the chart they would be interested in looking at, and maybe by default if from and to are not specified, we just default to the past 12 months.

I can see how this work will help drive frontend-to-backend shared data schema efforts as well.

**Comment by richaagarwal** [comment]
@klai95 Thanks for noting this, Kevin!  I've updated the issue's description above. Let me know if that captures this. In the future, we can certainly look into accommodating specific start and end dates as well. 

I also removed the bug label as this work is not yet released to production :)

**Comment by klai95** [comment]
> @klai95 Thanks for noting this, Kevin! I've updated the issue's description above. Let me know if that captures this. In the future, we can certainly look into accommodating specific start and end dates as well.
> 
> I also removed the bug label as this work is not yet released to production :)

Just two clarifying questions: 

(1) Does this mean we are set on not displaying the current month's data? I know during the meeting some folks were talking about prediction models, so just want to get some clarity!

(2) When you say we should filter installs data to the past n months, is there an upper bound for what n could be? For example, if someone requests for a value of 100 for n, do we have a set limit (say arbitrarily 36 just for example) that cannot be exceeded to limit the amount of data that needs to be returned? 

@richaagarwal

**Comment by richaagarwal** [comment]
@klai95 For our initial launch (what we've been referring to internally as P0 work), we won't be displaying the current month's data.  In follow-up work, there will likely be changes to what & how we display the data. 

We haven't yet discussed this particular ticket in a team meeting so it's possible there will be some more changes - nothing is set in stone at the moment, but we'll finalize the criteria for this ticket once we bring it into a sprint. At this time, I don't see too much value in adding an upper limit, but we can discuss more in refinement.

**Comment by richaagarwal** [comment]
Just a heads up that we may need to clarify whether to distinguish plugins that were released in the current month (in which case we'd check the plugin's release date and return data accordingly) vs. older plugins that happen to have zero installs - depending on the outcome of that, it may impact the work in this ticket (we could open up a separate issue, but just wanted to flag here). Let's clarify in sprint planning today.  cc @klai95 @neuromusic @codemonkey800 @liaprins-czi

**Comment by richaagarwal** [comment]
@klai95 @codemonkey800  To summarize what was discussed in sprint planning today - we will move forward with what's captured in Lia's designs and show a special message for when a plugin is new (e.g. released in the current month), and otherwise show data as defined in this ticket.  So I will let you two work out what the back-end should return so that the front-end knows it is a new plugin and to display the "There is not yet enough data..." message per [the design](https://www.figma.com/file/d3t84J9Uzmj0GZnYROzdQX/Activity-Dashboard?node-id=1356%3A2443#297017937).

**Comment by klai95** [comment]
> @klai95 @codemonkey800 Quick clarification - we actually never see zeros/no install data in Ben's table, because there's only a row for an item if it was an install. So unfortunately we don't have any way to meaningfully distinguish between "gaps" and zero installs. Based on discussions we've had so far, it seems we are comfortable inferring these as zero installs, so we should probably show this as zeroes in the UI as well.

@codemonkey800 Just some clarification, we would still want to return `None` instead of `0` in this case right?

**Comment by klai95** [comment]
> yeah it would be ideal to return `None` if there is a gap. I think the main use case is for when a plugin is less than a year old:
> 
> <img alt="image" width="375" src="https://user-images.githubusercontent.com/2176050/199320911-69185ee4-546d-4a3f-92f4-35264a3c2278.png">
> 
> in this case, there would be points for October - January, but the `y` values would be `None`.
> 
> another option we could do is have the backend only return the amount of points it has. so if there's only 6 data points, and we request 12, then just send 6. on the frontend we can fill in the remaining data points for the rest of the months and use `y: null` for the gaps

The second option is what we had before, so I think at this point perhaps we can just go with option 1?
