### ISSUE TITLE
Split.io feature flagging for backend

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#692]
Follow up of #619 to add Split.io feature flagging to the backend

[Tech Spec](https://docs.google.com/document/d/1M673LM8y3RHDK7GDQsGHSuq2dKToi-FVqEuKRtJIoPg/edit#heading=h.h1hb6dw6updw)

[Documentation](https://help.split.io/hc/en-us/articles/360020359652-Python-SDK)

**Comment by klai95** [comment]
Link: https://www.split.io/product/languages/python-sdk/

**Comment by klai95** [comment]
Sample Code:
```from splitio import get_factory
from splitio.exceptions import TimeoutException
factory = get_factory('YOUR_API_KEY')
try:
    factory.block_until_ready(5) # wait up to 5 seconds
except TimeoutException:
    # Now the user can choose whether to abort the whole execution, or just keep going
    # without a ready client, which if configured properly, should become ready at some point.
    pass
split = factory.client() ```

**Comment by klai95** [comment]
1: pip install 'splitio_client[redis,cpphash]==9.1.3'
2: Instantiate the SDK client with Redis enabled
- Our backend does not use Redis - look into alternative option

**Comment by klai95** [comment]
For future work, we would need to use `Multi-process mode` so that the API is a lambda and can have multiple different executions happening at a time, and `Redis` would be the only way to share the feature flag calls

**Comment by klai95** [comment]
Action Item 1: Create a `future work` ticket to capture https://github.com/chanzuckerberg/napari-hub/issues/692#issuecomment-1358240768

**Comment by klai95** [comment]
Action Item 2:  Follow step 1 and step 2 in https://github.com/chanzuckerberg/napari-hub/issues/692#issuecomment-1357948009 to set up split.io for backend

**Comment by klai95** [comment]
Action Item 3: Follow step 3 in https://github.com/chanzuckerberg/napari-hub/issues/692#issuecomment-1357948009 to start using the SDK for our use case(s)

**Comment by klai95** [comment]
https://github.com/chanzuckerberg/napari-hub/issues/810 has been created to capture `Setup split.io python client in napari hub backend`

**Comment by klai95** [comment]
https://github.com/chanzuckerberg/napari-hub/issues/811 has been created to capture `Validate feature flagging works by evaluating treatments for an API endpoint`

**Comment by richaagarwal** [comment]
@klai95 I'm going to archive this ticket from the board as you've created the follow-up tickets needed!

**Comment by klai95** [comment]
@richaagarwal Sounds good!
