### ISSUE TITLE
“Releases” section: Total number of releases

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#702]
template TBD.

"N updates since released X months ago"

**Comment by liaprins-czi** [comment]
(Not yet final) designs for P1 updates are here:
https://www.figma.com/file/d3t84J9Uzmj0GZnYROzdQX/Activity-Dashboard?node-id=1623%3A2042

**Comment by neuromusic** [comment]
shelving this due to technical limitations w/ pypi data
