### ISSUE TITLE
Adding keys to authenticate backend jobs

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#719]
### Discussed in https://github.com/chanzuckerberg/napari-hub/discussions/717

<div type='discussions-op-text'>

<sup>Originally posted by **manasaV3** October 31, 2022</sup>
Currently the backend jobs are unauthenticated. This would allow for anyone who is aware of the api end point to call it. As this is a more resource intensive workflow, we should secure the triggering of the backend data updating jobs at the earliest.

**Quick fix:**

- Add a secret key to our secrets manager. 
- Include the key in the header of the calls made from cloud watch events. 
- Verify if the valid key exists in our application before processing the POST request

**Long term fix:** 

- Update the cloud watch event to publish a message to sqs
- Update the lambda to have an sqs handler. 
- Run the valid job based on the sqs message triggering the lambda

Benefit of having the SQS over an API call is that we can have the failures in execution of the job handled more gracefully. We can also setup automated retries with limits. </div>

**Comment by neuromusic** [comment]
note: deleted the discussion since the issue is being tracked here now :D
