### ISSUE TITLE
Optimizing API endpoint for activity data

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#720]
### Summary
Currently, the frontend is making multiple calls to fetch data for loading several components of activity. This is not optimal, especially as all those data are related and we render them in the same place. This can be optimized for by having a single endpoint that returns all the data. 
### Intended Outcome
Proposed request path:

`/metrics/<plugin>?include="timeline","stats"&limit=25`

Proposed response structure:

```
{
    "activity": {
        "timeline": [
            {
                "timestamp": "10-1-2020",
                "installs": 2
            },
            {
                "timestamp": "11-1-2020",
                "installs": 0
            },
            {
                "timestamp": "12-1-2020",
                "installs": 12
            },
            ...
        ],
        "stats": {
            "totalInstalls": 500,
            "totalMonths": 15,
            "installInLast30Days": 100,
            ...
        }
    }
}
```

### How will it work?

Based on current data storage structures, we could fetch data from multiple different sources, filter the data by plugin and aggregate the response. This can be further optimized by updating how we store data.

**Comment by richaagarwal** [comment]
I see this is in review, but does a PR for the work in [this comment](https://github.com/chanzuckerberg/napari-hub/pull/741/files#r1022229640) need to be created first?

**Comment by manasaV3** [comment]
I believe it was set to review for https://github.com/chanzuckerberg/napari-hub/pull/741 

Now that https://github.com/chanzuckerberg/napari-hub/pull/749 has been merged, I can make a new PR to complete the cleanup. I can mark this issue closed after that. :)
