### ISSUE TITLE
Proposal: Maintain single data store for dev branches

### ISSUE THREAD

**Issue by richaagarwal** [chanzuckerberg/napari-hub#725]
Currently, we have folders within the `napari-hub-dev` S3 bucket specific to each dev branch.  Inside a specific dev branch folder, the structure otherwise mirrors what we have in `napari-hub-staging` and `napari-hub-prod` S3 buckets. I'd like to propose that we no longer maintain folders for each dev branch, and instead have all dev branches point to the same data. 

There are a few issues with our current process:
- Some cron jobs are more resource intensive the first time they run, as is the case with fetching npe2 metadata - ideally this would not be triggered with every new dev branch.
- Deploying a dev branch is currently a slow process, particularly due to needing to wait for a new S3 environment to be built / triggered by cron jobs.
- As we introduce more data sources and new nightly cron jobs (for instance with the activity dashboard work), there is an increased number of errors on our dev branches as expected data is not found - to restore functionality, the cron job must be manually triggered on that particular branch, or one must wait until the job has run on its schedule.

Some considerations:
- We would not want cron jobs to be running on every single dev branch with this model, as it would be redundant & they may attempt to write to the same location at the same time, so it might be worth considering a persistent `dev-` branch that has cron jobs enabled, and disabling them on any other dev branch.
- Testing functionality related to the cron jobs specifically would then be limited to such a branch, which would be a tradeoff that seems manageable
- Though this ticket is specific to our current S3 architecture, the problem & solution would still apply if/when we move to a database architecture (e.g. we would not want to maintain branch-specific schemas within a dev database and instead should read/write from the same dev resource).

If we were to move forward with this, I believe most of the complexity would be in updating the terraform config such that a single `dev` branch triggers cron jobs and no other.  In reading/writing to S3, I believe it would be a simple change in terms of removing references to `BUCKET_PATH` in https://github.com/chanzuckerberg/napari-hub/blob/main/backend/api/s3.py. `BUCKET_PATH` is only set on dev lambdas, specifically for this purpose, and is not set for prod and staging, so it should be a harmless change.

Curious if anyone else has thoughts, concerns, or other ideas on how best to solve this issue. cc @klai95 @codemonkey800 @manasaV3 @DragaDoncila

**Comment by richaagarwal** [comment]
For now, we have agreed on a process change to limit our usage of dev branches to a single, shared one, `dev-shared`.  I will add notes to our wiki and close this out once that's done.

**Comment by richaagarwal** [comment]
I have updated the wiki - the diff can be viewed here: https://github.com/chanzuckerberg/napari-hub/wiki/Eng:-Deployment-Environments/_compare/18d569df5feda594c7eb31bd3624a8131a0bc3cd...7d2f5867022f7df3975f9ed1e55962879c1363fa

@klai95 @codemonkey800 If those changes look good to you, let me know and I will close this out.  If you have any feedback, feel free to comment here.

**Comment by klai95** [comment]
@richaagarwal Looks good to me and sounds like a good plan!
