### ISSUE TITLE
Change copy for total installs section

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#751]
Got some feedback from @LCObus to change the copy for the total installs section from `over` -> `around`

<img width="257" alt="image" src="https://user-images.githubusercontent.com/2176050/202005655-3f0d0662-b00d-4119-95ad-8436c095591b.png">

**Comment by LCObus** [comment]
I assume/hope we'll have background details on where we pull data from, how regularly, etc, perhaps in the form of a hover over "i" icon?

 I imagine the "over" or even "around" was done to create buffer around when you update the info, but I'm curious what constructs the team decided on? Any ability to create clarity/definition for user is ideal, reducing cognitive load.

I also assume "publically released" is to account for differentiation between to pypi? or future proof grey market plugins? but it's confusing/vague. Now im unsure if this includes pypi, which would be valuable to include as it contributes to the goal to enable user to assess algorithmic usage since dissemination, a proxy for popularity.

**Comment by richaagarwal** [comment]
The initial release date does not change, so to my knowledge this wasn't done to create buffer around when we update the info.  It's moreso that there are these different buckets that @liaprins-czi  had identified (though having trouble finding the initial doc at the moment). If we wanted to be more specific we could be from a data perspective.

**Comment by neuromusic** [comment]
> I assume/hope we'll have background details on where we pull data from, how regularly, etc, perhaps in the form of a hover over "i" icon? 

We'll have a link at the bottom to an page with details on how we source the data:
https://www.figma.com/file/d3t84J9Uzmj0GZnYROzdQX/Activity-Dashboard?node-id=1121%3A1819&t=dOp9sAcCUdNMG62m-0

> I also assume "publically released" is to account for differentiation between to pypi?
Publicly released is equivalent to release on PyPI

**Comment by LCObus** [comment]
thanks @neuromusic ! Of course this is written down somewhere and I just didnt see it 🤦‍♀️.
My original recommendation stands- that "over" as a defining term is a lower bound, and without knowing the bucket system, may prove confusing/insufficiently specific to user needs.

**Comment by liaprins-czi** [comment]
> It's moreso that there are these different buckets that @liaprins-czi had identified (though having trouble finding the initial doc at the moment)

It was originally brought up by @kandarpksk and / or @neuromusic as a way to be less granular as a plugin gets "older", (but either of you add more context / correct me if I'm mis-representing anything). The final time buckets were decided in an Activity Dashboard sync mtg, with @neuromusic + @kandarpksk ; [here's a link to the original comment in the G-doc for context](https://docs.google.com/document/d/11QrzXGAmmHwuQBnljaIKxhyAkeAElaCZR2aCRay8Ykg/edit?disco=AAAAhYVdyPo), where I documented what we'd decided, and [here's a link to where I mocked up all the time-granularity buckets for the final design](https://www.figma.com/file/d3t84J9Uzmj0GZnYROzdQX/Activity-Dashboard?node-id=1357%3A2021&t=jc69vx5mW1YjFjqT-4).

We could change to be "less than"; if time we can re-discuss in today's sync mtg.

**Comment by LCObus** [comment]
Thanks for the decision context @liaprins-czi ! 
I understand the granularity issue, though I still believe the user's goal of understanding usage at a snapshot in time is not well serviced by a single bounding limit. I think "less than" would cause the same issue- one bounding limit but creating confusion about how big the upper limit is.

It may not be an issue, I'm simply sharing my response as an outsider looking at the data and trying to put myself in a new first time dashboard user's shoes.
