### ISSUE TITLE
Give insight into maintenance of plugins

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#807]
### Summary
Following up on #500 we plan to add metrics on Github activity.

### Intended Outcome
Plugin users will gain insight into maintenance being performed on plugins (and core libraries that they are built upon).

### How it will work
We will source data from Github and present visualizations of commit activity under the Activity Tab.

### User Stories

- [P0] As a plugin user, when I'm viewing a plugin's activity, I want to be able to see the total number of commits made to the plugin (and its core package) since the repo was created.
- [P0] As a plugin user, when I'm viewing a plugin's activity, I want to be able to see when the latest commit occurred for the plugin (or its core package).
- [P0] As a plugin user, when I'm viewing a plugin's activity, I want to be able to see how commit activity has varied over the past year.
- [P1] As a plugin developer who's plugin wrap a core library, when I am specifying metadata for my plugin, I want a way to specify a core package so that my plugin's "Maintenance" metrics reflect my work upstream.

### Acceptance criteria

- Looks and functions according to designs captured in https://www.figma.com/file/d3t84J9Uzmj0GZnYROzdQX/Activity-Dashboard?node-id=1912%3A4299&t=KM7mAiENlSFMIDW8-0

### Tasks

- [ ] #809

**Comment by richaagarwal** [comment]
@neuromusic As P0 work has been completed on this, when do you think would be an appropriate time to close out the epic?  I'm also curious at what stage (if at all) we'd want to bring in P1 work.

**Comment by neuromusic** [comment]
@richaagarwal since #809 has been opened, I think we can close this epic and track remaining work there
