### ISSUE TITLE
Validate feature flagging works by evaluating treatments for an API endpoint

### ISSUE THREAD

**Issue by klai95** [chanzuckerberg/napari-hub#811]
### Summary
After https://github.com/chanzuckerberg/napari-hub/issues/810 is completed, the next step is to use the SDK to evaluate treatments for our backend API endpoints.

### Intended Outcome
- When we turn off an API endpoint, the select functionality for the API endpoint would be turned off during runtime
- When we turn on an API endpoint, the select functionality for the API endpoint would be turned on during runtime

### Note
- This ticket can only be worked on after https://github.com/chanzuckerberg/napari-hub/issues/810 is completed
-  There may be a need in the future to choose when and to which users new code is delivered via feature flagging

**Comment by klai95** [comment]
General logic for the ticket: 
```treatment = client.getTreatment('SPLIT_NAME');
if (treatment == 'on') {
    // insert code here to show on treatment
} else if (treatment == 'off') {
    // insert code here to show off treatment
} else {
    // insert your control treatment code here
}

**Comment by EricMaxWang** [comment]
Decision from refinement call to focus on one endpoint

**Comment by klai95** [comment]
As discussed in the backlog refinement meeting today, we are closing this issue. Moving forward, we will be updating our APIs to use feature flags as needed. For now, we have the `use_dynamo` and `use_s3` treatments, but we may add more treatments in the future as needed. Please check out https://github.com/chanzuckerberg/napari-hub/issues/859 for reference. If there is anything you would like to add, please do chime in. @codemonkey800 @EricMaxWang @manasaV3

**Comment by richaagarwal** [comment]
@klai95 @manasaV3 @codemonkey800 I thought this ticket, together with https://github.com/chanzuckerberg/napari-hub/issues/810, were meant for setting up Split.io in the backend?  I think we could leave this open but move it into the backlog instead of the "Ready" column. Let me know what you all think.
