### ISSUE TITLE
View latest commits made to plugin

### ISSUE THREAD

**Issue by klai95** [chanzuckerberg/napari-hub#819]
### Summary
- As a plugin user, when I'm viewing a plugin's activity, I want to be able to see when the latest commit occurred for the plugin (or its core package)

### Intended Outcomes
- The SQL query has been written to execute the requirement of this ticket.
- Backend has implemented code to run said SQL query on a daily basis to ensure data is updated.
- Backend has surfaced relevant endpoints for said data for frontend to display on the `Activity` tab.

### Note
- The SQL query and Snowflake output generated by SQL query are commented on this ticket.

### Links
- [Epic](https://github.com/chanzuckerberg/napari-hub/issues/807)
- [Design](https://www.figma.com/file/d3t84J9Uzmj0GZnYROzdQX/Activity-Dashboard?node-id=1912%3A4299)
- [Document](https://docs.google.com/document/d/1PG3hld19fdZSC7c57gBfg_MouOGcd-GC6GVj0EaRq-4/edit)
- [PR](https://github.com/chanzuckerberg/napari-hub/pull/832)

**Comment by klai95** [comment]
SQL query for this ticket:
```
 select repo, date_trunc('month', to_date(commit_author_date)) as month, count(*) as num_commits
 from imaging.github.commits
 where repo_type = 'plugin'
 group by 1,2

**Comment by klai95** [comment]
Snowflake output generated by SQL query:

<img width="1441" alt="Screen Shot 2023-01-06 at 2 55 44 PM" src="https://user-images.githubusercontent.com/70177777/211098467-c157d564-9616-44d5-8c9e-e839a094ff42.png">

**Comment by klai95** [comment]
As verified by Ben in [this Slack conversation](https://czi-sci.slack.com/archives/C025V5TPDAL/p1672862449724019) with the Trust Team, there is no concern for posting SQL queries to the napari-hub repo.

**Comment by EricMaxWang** [comment]
Note from sprint planning meeting on Mon, 1/9:

- consideration for shifting granularity of this 'latest commit' to be "within the last week" vs. "within the past day"
- update description w/ consideration of a lag in 24 hr data freshness


CONFIRMED:
- [Lia] "within the last week"

**Comment by klai95** [comment]
PR for this ticket has been created: https://github.com/chanzuckerberg/napari-hub/pull/830

**Comment by manasaV3** [comment]
To solve for plugin name differing from the repository name:

- Load cache/index.json into memory
- Create a dictionary with the key as code_repository and value plugin name
- Perform metric fetch from snowflake
- Translate code_repository to the plugin name
- Write to metric cache

**Comment by klai95** [comment]
Proposed request path:

/metrics/<plugin>?include="timeline","stats"&limit=25

Proposed response structure:

{
   "usage":{
      "timeline":[
         {
            "timestamp":1669852800000,
            "installs":1
         }
      ],
      "stats":{
         "totalInstalls":70,
         "installsInLast30Days":7
      }
   },
   "maintenance":{
      "stats":{
         "latest_commit":"2023-01-10 23:15:15"
      }
   }
}

**Comment by klai95** [comment]
`/metrics/{napari-mm3}` endpoint response:

```
{
  "maintenance": {
    "stats": {
      "latest_commit": "2023-01-10 23:15:15"
    }
  },
  "usage": {
    "stats": {
      "installsInLast30Days": 7,
      "totalInstalls": 70
    },
    "timeline": [
      {
        "installs": 0,
        "timestamp": 1640995200000
      },
      {
        "installs": 0,
        "timestamp": 1643673600000
      },
      {
        "installs": 0,
        "timestamp": 1646092800000
      },
      {
        "installs": 0,
        "timestamp": 1648771200000
      },
      {
        "installs": 0,
        "timestamp": 1651363200000
      },
      {
        "installs": 20,
        "timestamp": 1654041600000
      },
      {
        "installs": 6,
        "timestamp": 1656633600000
      },
      {
        "installs": 2,
        "timestamp": 1659312000000
      },
      {
        "installs": 4,
        "timestamp": 1661990400000
      },
      {
        "installs": 26,
        "timestamp": 1664582400000
      },
      {
        "installs": 4,
        "timestamp": 1667260800000
      },
      {
        "installs": 1,
        "timestamp": 1669852800000
      }
    ]
  }
}

**Comment by manasaV3** [comment]
We should not have both camelCase and snake case in the same response. We should make it all consistent. 
We use snake_case in other parts of this application, so we could update the camel case attributes to follow suit. 

@codemonkey800  What are your thoughts on that? 

Also, it would be good to call out what the clients are to expect in the case that a last commit date is not available.

**Comment by manasaV3** [comment]
In the usage component, we have the timestamp as a number, but for the latest commit, it is a string. They are both similar fields. So, why are we representing them in different formats?
@codemonkey800 Would having that be an epoch timestamp here be helpful with i18n?

**Comment by richaagarwal** [comment]
Moving this into our new "Pending QA & Release" column, and reopening. Going forward, we can close tickets once they've gone through release & QA

**Comment by klai95** [comment]
@richaagarwal Sounds good to me! I will make the necessary comments and changes for the other two PRs
