### ISSUE TITLE
Integrate backend for maintenance section of activity dashboard

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#838]
When #824, #825, and #826 are closed, we should be ready to start integration the backend with the frontend as soon as the backend is ready.

Right now the UI uses static data to render everything, so we'll have to replace all of the static data with hooks that make API calls to the backend.

**Comment by klai95** [comment]
The response for activity dashboard endpoint will be structured in the following way:
`{'usage': usage_data, 'maintenance': maintenance_data}`
