### ISSUE TITLE
Pull request template

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#841]
Our pull request guidelines currently lives in the [CONTRIBUTING.md](https://github.com/chanzuckerberg/napari-hub/blob/main/CONTRIBUTING.md) docs, but may not be as visible as we thought. We should look into creating a PR template that includes suggested sections and the list of best practices

**Comment by richaagarwal** [comment]
@codemonkey800 For sure! I agree, I think we can broaden the language in the template to include these different cases. I have some language in mind and can open up a PR for this a little later!
