### ISSUE TITLE
Migrate data store from S3 to DynamoDB

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#845]
Currently, the persistence of data for napari-hub.org is done by storing the files in S3. This has been sufficient in supporting features like fetching all data related to a plugin. However, it becomes expensive to fetch specific data about a plugin, making it difficult to query across multiple plugins by criteria. It also limits our ability to optimize the data refresh and support functionalities.

Based on the support we need, we have identified DynamoDB as the best option in place of S3. 

##### Related Tasks:

-  #818
- #869
- #953
- #706 
- #707

Install Activity Migration:

- chanzuckerberg/imaging-tech-analytics#49
- #867 
- #852
- #853
- #854
- #855
- #856
- #966 

GitHub Activity Migration:

- #921
- #922
- #923
- #968

##### Category Migration:

- #858
- #866
- #859
- #969
- #1057

##### Plugin Migration:
- #880
- #860
- #861
- #862
- #882
- #881
- #864
- #970
- #950

~~#857 (deprioritized/not needed for now)~~
~~#949 (deprioritized/not needed for now)~~
~~#951 (deprioritized/not needed for now)~~
~~#952 (deprioritized/not needed for now)~~

**Comment by manasaV3** [comment]
##### Related Tasks:

- [Adding backend API tests](https://github.com/chanzuckerberg/napari-hub/issues/818)
- Add Documentation 


##### Category Migration:

- [Create category dynamoDB Infrastructure and seed data#858](https://github.com/chanzuckerberg/napari-hub/issues/858)
- [Update category API to use dynamoDB#859](https://github.com/chanzuckerberg/napari-hub/issues/859)


##### Metrics Install Activity Migration:

- Update the snowflake schema to include ingestion_timestamps on records on install activity
- [Create activity install ETL workflow Infrastructure#852](https://github.com/chanzuckerberg/napari-hub/issues/852)
- [Create activity install ETL workflow#853](https://github.com/chanzuckerberg/napari-hub/issues/853)
- [Update metric API for usage.stats.total_installs#854](https://github.com/chanzuckerberg/napari-hub/issues/854)
- [Update metric API for usage.stats.installs_in_last_30_days#855](https://github.com/chanzuckerberg/napari-hub/issues/855)
- [Update metric API for usage.timeline to use dynamoDB#856](https://github.com/chanzuckerberg/napari-hub/issues/856)
- [Update metric API to support usage.stats.initial_release_date using dynamoDB#857](https://github.com/chanzuckerberg/napari-hub/issues/857)


##### Plugin Migration:
- [Create plugin ETL workflow Infrastructure#860](https://github.com/chanzuckerberg/napari-hub/issues/860)
- [Create plugin ETL workflow for fetching github and pypi data to write to dynamoDB#861](https://github.com/chanzuckerberg/napari-hub/issues/861)
- [Update plugin workflow for fetching plugin data to write to dynamoDB#862](https://github.com/chanzuckerberg/napari-hub/issues/862)
- [Update plugins listing API endpoints to use dynamoDB#863](https://github.com/chanzuckerberg/napari-hub/issues/863)
- [Update plugin data API endpoint to use dynamoDB#864](https://github.com/chanzuckerberg/napari-hub/issues/864)

**Comment by richaagarwal** [comment]
Current sprint: Wrap up activity migration, start (& finish) GitHub metrics & Category migration, start Plugin migration
Next sprint: Wrap up Plugin migration & start Citations schema

**Comment by richaagarwal** [comment]
Current sprint: Wrap up install activity, github activity, & category migration.  Begin plugin work.
Next sprint: Wrap up plugin work.

**Comment by manasaV3** [comment]
Checklist to ensure all s3 data references have been migrated: 
- [ ] migrate references to plugin_index  file in data workflow

**Comment by richaagarwal** [comment]
Closing this out, as we'll use https://github.com/chanzuckerberg/napari-hub/issues/1131 to track related deprecation and clean-up work. 

There is one remaining ticket for adding plugin documentation, but we can use that ticket directly to track its progress: https://github.com/chanzuckerberg/napari-hub/issues/970

**Comment by manasaV3** [comment]
Relates to https://github.com/chanzuckerberg/napari-hub/issues/1155
