### ISSUE TITLE
remove my plugin napari-aphid from napari-hub

### ISSUE THREAD

**Issue by hereariim** [chanzuckerberg/napari-hub#846]
Hello,
I want to keep visible my plugin in PyPI but not be visible on the napari hub. Could you remove my plugin from napari-hub ? please.
I appreciate your help.
Thank you.
Best,

**Comment by aganders3** [comment]
Hi @hereariim - I think the [PR I opened on your repo](https://github.com/hereariim/napari-aphid/pull/2
) is all you need to configure your plugin visibility as you'd like.

See https://github.com/chanzuckerberg/napari-hub/wiki/Customizing-your-plugin's-listing#visibility for more information on customizing your plugin on napari-hub.
