### ISSUE TITLE
Create activity install  ETL workflow

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#853]
In the new lambda's handler’s check if the invoking sqs message is for activity. If yes, execute the ETL.

- Fetch the `last_updated_timestamp` from the parameter store.
- Query snowflake view for all records inserted with ingestion timestamp after the `last_updated_timestamp` and until `current_timestamp`
- Transform the results into dynamo record of type DAY. Batch write all the records to dynamo.
- For all the plugins with new install activity, query snowflake for the install activity at a month level granularity for the months that had new records inserted. 
- Transform the results into dynamo record of type MONTH. Batch write all the records to dynamo.
- Query snowflake for the total installs for all the plugins with new install activity. 
- Transform the results into dynamo record of type TOTAL. Batch write all the records to dynamo.
- Update the parameter store with the `current_timestamp`

Some of data that could be useful to have logged:
- Time taken for each snowflake query
- Time taken for dynamo writes
- Number of records in each batch write
- Exceptions encountered

**Comment by klai95** [comment]
Where can I find the schema for this ticket?

**Comment by richaagarwal** [comment]
@klai95 This is a part of the "install activity migration" work outlined in #845, the schema is referenced in https://github.com/chanzuckerberg/napari-hub/issues/867
