### ISSUE TITLE
Update plugin API endpoints to use dynamoDB

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#863]
### /plugins
Should return only public plugins
e.g. visibility == 'public' and is_blocked == False

- https://github.com/chanzuckerberg/napari-hub/issues/949

### /plugins/index
Should return only public plugins metadata as a list
e.g. visibility == 'public' and is_blocked == False

- https://github.com/chanzuckerberg/napari-hub/issues/950

### /plugins/excluded
Should return non-public plugins 
e.g. visibility != 'public'

- https://github.com/chanzuckerberg/napari-hub/issues/951

### /plugins/\<plugin\>/versions/\<version\>
Should only return plugin data if it has public or hidden visibility and is not blocked.
e.g. visibility IN ('public', 'hidden')  and is_blocked == False

- https://github.com/chanzuckerberg/napari-hub/issues/864

### /manifest/\<plugin\>/versions/\<version\>
- https://github.com/chanzuckerberg/napari-hub/issues/952

#### Notes:
If collaborating on this in parallel, creating the pynamo models for `plugin`, and `plugin-excluded` should be done first.

**Comment by richaagarwal** [comment]
Closing this ticket out as it's redundant with the info provided in the epic - https://github.com/chanzuckerberg/napari-hub/issues/845 - and to avoid having to update info in two places.
