### ISSUE TITLE
Update privacy policy

### ISSUE THREAD

**Issue by richaagarwal** [chanzuckerberg/napari-hub#868]
Update [Privacy Policy](https://www.napari-hub.org/privacy) for napari hub with language provided here: https://docs.google.com/document/d/1oRd_6o4HgsRJTIWnNccDYR3dSCCbJxhlvI2ScNr3A0k/edit#heading=h.n43g0ufvgqwz

**Comment by EricMaxWang** [comment]
Reference for one-liner blurb
https://github.com/chanzuckerberg/napari-hub/pull/690

**Comment by klai95** [comment]
Link to PR: https://github.com/chanzuckerberg/napari-hub/pull/904

**Comment by richaagarwal** [comment]
Closing this out as it was deployed with today's release - FYI @EricMaxWang

**Comment by EricMaxWang** [comment]
Thanks all!
