### ISSUE TITLE
Use dynamodb by passing query parameter from frontend

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#869]
To use dynamodb from backend, we can pass a query parameter from the frontend to use it

We will set up separate feature flags for each data vertical in Manasa's comment below

Possible variable names to pass into the API call:
`use_dynamo`
`use_s3`

**Comment by manasaV3** [comment]
Having a stand-alone feature flag for each of the data verticals, ie, category, activity, and plugin, will provide us with more granular access control. Could we run into any potential issues in setting it up that way?

**Comment by richaagarwal** [comment]
Moving this into the "Ready" column for visibility. Please feel free to discuss & point this one when you all sync up tomorrow!

**Comment by manasaV3** [comment]
METRICS_USAGE_MIGRATION, use_s3_usage, /metrics, use s3 for usage data, use dynamo for usage data
METRICS_MAINTAINENCE_MIGRATION, use_s3_maintainence, /metrics, use s3 for maintainence data, use dynamo for maintainence data

CATEGORIES_MIGRATION, use_s3_categories, /categories /categories/\<category\> /categories/\<category\>/versions/\<version\>, use s3 for category data, use dynamo for category data
PLUGIN_MIGRATION, use_s3_plugin, /plugin/index /plugin/\<plugin\> /plugin/\<plugin\>/versions/\<version\>, use s3 for plugin data, use dynamo for plugin data
