### ISSUE TITLE
Add human readable alias support for backend dev environment

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#872]
Add human-readable alias support for backend dev environment to help easier debugging and backend integration tests.

**Comment by richaagarwal** [comment]
Very cool! I think for this to technically be complete in the dev environment, the latest changes need to be applied to `dev-shared` as well, and then I think https://api.dev.napari-hub.org/dev-shared/ would work. Is that right?

**Comment by manasaV3** [comment]
Deploying changes to `dev-shared` and tested changes work https://api.dev.napari-hub.org/dev-shared/
