### ISSUE TITLE
Empty activity maintenance section when no github URL specified

### ISSUE THREAD

**Issue by richaagarwal** [chanzuckerberg/napari-hub#890]
Currently, ~5% of napari hub plugins are not associated with a github URL (what we track as `code_repository`). Below is the full list of these plugins. Navigating to an impacted plugin's activity tab, e.g. https://staging.napari-hub.org/plugins/napari-annotate, displays this data for the maintenance section.  Instead, we should come up with a more informative design, indicating that this plugin does not have a code repository specified.

<img width="852" alt="Screenshot 2023-02-07 at 1 42 35 PM" src="https://user-images.githubusercontent.com/354591/217373403-ddd1c854-52a6-47d5-94cc-36197fd2732c.png">

Plugins without a github repository specified
```
okapi-em
napari-annotate
napari-tissuumaps
grabber-ift
napari-microscope
napari-live-flim
avidaq
napari-apr-viewer
napari-mri
napari-pram
faser
napari-kics
napari-proofread-brainbow
napari-bioimageio
imaxt-multiscale-plugin
```

**Comment by richaagarwal** [comment]
@Janeece Could you take a look at this one?  It's distinct from https://github.com/chanzuckerberg/napari-hub/issues/889

**Comment by Janeece** [comment]
@richaagarwal I think we could use the graybox pattern Lia developed to replace all of the content impacted (ex: if its all activity, only show gray box; if it's specific activity sections, display the section title and replace content with the gray box). Messaging would need updating to something like "Metrics not available, this plugin does not have a code repository specified." — whatever makes it clear that this isn't temporary + why. 

This recommendation depends on if we can tell this is the cause for no data (seems like we can?).
Let me know if you want me to mock it up!

![Screenshot 2023-02-07 at 2 37 10 PM](https://user-images.githubusercontent.com/63013360/217382794-5a0d75ff-ae9d-4f52-9864-07533cd3af76.png)

**Comment by richaagarwal** [comment]
@Janeece That makes sense to me - and yes, we can confirm the cause by looking at whether or not the plugin's `code_repository` is null.  

@codemonkey800 Do you feel like you have sufficient information to address this?  I think you could use the `code_repository` field that you already have access to via the `PluginData` interface, but feel free to coordinate with @klai95 if you think a back-end change is necessary.

**Comment by richaagarwal** [comment]
Closing this out as it was deployed to prod with today's release - I checked https://www.napari-hub.org/plugins/napari-annotate and it looks good 🎉
