### ISSUE TITLE
napari hub SEO improvements

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#894]
Epic for tracking all tasks related to implementing the recommended SEO improvements from the Digital Technology Team.

## Links
- [SEO intake notes](https://docs.google.com/document/d/1OYJAvkC87Ao69CNGKtHUy73tqVsRo0TDSznH1cgFnfw/edit#heading=h.rwrsgy120r2r)
- [SEMRUSH Report](https://drive.google.com/file/d/1KAgLbUn1HNjgTpj1YK46WpISNtdiVB5m/view)
- [napari hub SEO recommendations](https://docs.google.com/document/d/196hpCC_CnOniUPtQG1iOeywEaZWQX7Bmt7bea4l8cpM/edit#heading=h.yaucjpma3xx)
- [SEO kickoff notes](https://docs.google.com/document/d/1Ylar8JyrHxTe5HKLV24V3R-BrEvsqE_ah8hBaSYEkZI/edit#heading=h.ymhhtlregtiz)
- [Hub Metadata Titles](https://docs.google.com/document/d/1pfkk6_8vY_8YcU4budv7AnZ_KLEQawHY67VJfT7YtR0/edit#heading=h.n0obsym12ejl)

### MVP

- [x] #895
- [x] #896
- [x] #897
- [x] #898
- [x] #899
- [x] #900
- [x] #932 

### Nice to have

- [ ] #907 
- [ ] #905
- [ ] #678
- [ ] #929 
- [ ] #930 
- [ ] #931

**Comment by richaagarwal** [comment]
Closing this out, but let's keep "nice to have" items in mind for future work @codemonkey800!
