### ISSUE TITLE
Create optimized titles and descriptions for each page

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#895]
Pages on the napari hub currently have titles and descriptions that are not optimal for SEO. The titles for each page have the following formats:

| Page                                                             | Page Title                                                        |
| ---------------------------------------------------------------- | ----------------------------------------------------------------- |
| [Home](https://www.napari-hub.org)                               | `napari hub \| search`                                            |
| [Plugin](https://www.napari-hub.org/plugins/napari-ism)          | `napari hub \| plugins \| napari-ism by Alessandro Zunino`        |
| [About](https://www.napari-hub.org/about)                        | `napari hub \| About`                                             |
| [FAQ](https://www.napari-hub.org/faq)                            | `napari hub \| FAQ`                                               |
| [Privacy](https://www.napari-hub.org/privacy)                    | `napari hub \| Privacy`                                           |
| [Contact](https://www.napari-hub.org/contact)                    | `napari hub \| Contact`                                           |
| [Collections Home](https://www.napari-hub.org/collections)       | `napari hub \| collections`                                       |
| [Collection](https://www.napari-hub.org/collections/alfa-cohort) | `napari hub \| collections \| Segmentation Plugins by the Alf...` |

The current suggestion is to:

1. Use dash instead of pipe for titles
2. Place target keywords at beginning of title
3. Limit titles to 51 - 60 characters
4. Limit descriptions to 150 - 160 characters

For example:

- https://www.napari-hub.org/plugins/stardist-napari
- Current meta title:  `napari hub | plugin | stardist-napari by Uwe Schmidt, Martin Weigert`
- Suggested meta title:  `stardist napari by Uwe Schmidt, Martin Weigert - plugins`

We can change the title / description to match the format specified in Danielle's [Hub metadata doc](https://docs.google.com/document/d/1pfkk6_8vY_8YcU4budv7AnZ_KLEQawHY67VJfT7YtR0/edit#heading=h.n0obsym12ejl).

**Comment by EricMaxWang** [comment]
'Ready' pending edits to @dgmccart's metadata doc. Kevin will work on other two tickets first.

**Comment by klai95** [comment]
PR for this issue: https://github.com/chanzuckerberg/napari-hub/pull/961
