### ISSUE TITLE
Use canonical links

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#896]
https://ahrefs.com/blog/canonicalization/

Canonical links is a way for us to specify the primary URL for all pages that can be derived from a single authoritative URL. This is important for the following scenarios:

1. Faceted navigation on home page: Given the search page is driven by search, filters, sort, and pagination, there can be a large combination of possible URLs because of the different possible query parameters. For example:
https://www.napari-hub.org/?search=napari&sort=relevance&license=oss&supportedData=2D&page=1
2. Plugin page category highlighting: When filtering by npe2 metadata, the hub will add additional query parameters to the URL to highlight the filtered metadata. For example: 
https://www.napari-hub.org/plugins/napari-stracking?workflowStep=Object+tracking
3. Prevent aliased deployments from being indexed on Google, like https://public-frontend.prod.imaging.cziscience.com

Because of this, it's important we specify a canonical URL for each page so that it points directly to the napari hub.

**Comment by klai95** [comment]
@codemonkey800 Could you also provide a screenshot of the current behavior? I think it would make it more clear visually what the problem is.
