### ISSUE TITLE
Update sitemap.xml

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#897]
The existing `sitemap.xml` file for the napari hub currently has invalid data in the URL:

https://www.napari-hub.org/sitemap.xml

<img width="808" alt="image" src="https://user-images.githubusercontent.com/2176050/217701268-84f006c2-11ca-4a20-a725-7e8da031c581.png">

Everything else in the `sitemap.xml`, however, is correct. We'll need to update the logic for the `sitemap.xml` file to also fetch each collection and generate it for each collection in the file, similar to how we do it for plugins:

https://github.com/chanzuckerberg/napari-hub/blob/36f7ce20c04b5e5862d60dbda7fdf6dc9d5fd84a/frontend/src/pages/sitemap.xml.ts#L81-L102

**Comment by klai95** [comment]
PR for this ticket: https://github.com/chanzuckerberg/napari-hub/pull/915
