### ISSUE TITLE
Improve lighthouse SEO, Best Practices, and Accessibility scores

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#898]
Several of our lighthouse mobile scores could be improved to improve our SEO. Performance will need to be tackled in the future given how complex it is to profile and fix performance issues 

### How to run Lighthouse test

To run a Lighthouse test for any page:

1. Install [Lighthouse extension](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=en)
2. Go to [Manage Extensions](chrome://extensions/?id=blipmdconlkpinefehnmjammfjpmpbjk)
3. Enable Lighthouse for Incognito. This is because your other extensions might impact the Lighthouse scores:
    <img width="679" alt="image" src="https://user-images.githubusercontent.com/2176050/217704321-c02ac6dc-a00e-4115-962b-23a99751a604.png">
4. Open Incognito Chrome
5. Open napari hub page
6. Open Chrome Dev Tools
7. Go To Lighthouse
    <img width="568" alt="image" src="https://user-images.githubusercontent.com/2176050/217704447-685bbce8-bd80-4044-9ab0-5b729b5900da.png">
9. Start load test with these settings
    <img width="565" alt="image" src="https://user-images.githubusercontent.com/2176050/217704400-41993e6d-f59c-4d44-981f-8a8c26aea945.png">

### Lighthouse Scores for each page

<img width="566" alt="image" src="https://user-images.githubusercontent.com/2176050/217703923-130eea0c-70be-4c30-8a6b-11d76926de13.png">
<img width="565" alt="image" src="https://user-images.githubusercontent.com/2176050/217704094-e001dc78-2c7e-4dc4-906b-e6de8723ffc8.png">
<img width="562" alt="image" src="https://user-images.githubusercontent.com/2176050/217704867-2e3a6163-ca96-4865-989c-377b557c3640.png">
<img width="565" alt="image" src="https://user-images.githubusercontent.com/2176050/217704932-cb03c0a9-e39b-4910-b276-435e5e427456.png">
<img width="563" alt="image" src="https://user-images.githubusercontent.com/2176050/217703981-cf1d8949-34ea-4fcd-81f7-1d30def72da5.png">
<img width="564" alt="image" src="https://user-images.githubusercontent.com/2176050/217704019-415d8b3c-9a7b-4c8c-bb78-01a25bebff65.png">
<img width="566" alt="image" src="https://user-images.githubusercontent.com/2176050/217704725-f8a79e0d-4705-4408-b854-80675885b178.png">
<img width="565" alt="image" src="https://user-images.githubusercontent.com/2176050/217704794-81e99f21-1bfe-4c92-a258-68d1a33ebbcc.png">

**Comment by EricMaxWang** [comment]
@codemonkey800 to define this ticket specific to SEO, Accessibility, Best Practices as Lighthouse is more specific on insights to how we can improve. A new ticket will be created for Performance; requires more evaluation and monitoring.
