### ISSUE TITLE
Add Open Graph meta tags to each page

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#900]
Open Graph meta tags allow us to enrich the appearance of links on social media. We currently have Open Graph tags implemented for collections: https://github.com/chanzuckerberg/napari-hub/pull/553

But we do not have it for other pages. The main things we can add to the Open Graph tags are:

- Title
- Type
- URL
- Image
- Description

https://github.com/chanzuckerberg/napari-hub/blob/36f7ce20c04b5e5862d60dbda7fdf6dc9d5fd84a/frontend/src/pages/collections/%5Bsymbol%5D.tsx#L84-L102

**Comment by EricMaxWang** [comment]
@codemonkey800 split ticket into different tickets for: metadata vs. image service
