### ISSUE TITLE
Create github-activity dynamoDB table

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#921]
Create a dynamo table `github-activity` with range and sort keys as specified in the schema.

### Schema

plugin_name - range key (name of the plugin)
type_identifier - sort key

| Field name  |  Attribute type |  Description |  Example |
| ----------- | ----------- | ----------- | ----------- |
| plugin_name      | String  | ~Range~ Hash Key  |  foo
| type_identifier   | String  | Sort Key |  LATEST:bar/baz, MONTH:202302:bar/baz, TOTAL:bar/baz
| timestamp | Number | Holds value for the latest timestamp in milliseconds.  |  1678132844
| number_of_commits | Number | Holds value for the number_of_commits. Part of the MONTH record  |  10
| repo | String | Name of the repository  |  bar/baz
| last_updated_timestamp | Number | timestamp of when the record was last updated | 1678132839

The timestamp record holds the value for period, when the record of `type=MONTH` and the latest commits's timestamp value when `type=LATEST`

The new dynamo table should have a prefix. If the environment is dev, the prefix should be the stack name. If the environment is staging or prod, the environment can be the prefix. Pass the prefix to the backend lambda.

#### IAM permission

The existing backend lambda should be given permission to perform query and getItem actions on the `github-activity` dynamo table. The data workflow lambda should be given permission to batch write to the `github-activity` table.

**Comment by manasaV3** [comment]
Similar to #867

**Comment by klai95** [comment]
> Create a dynamo table `github-activity` with range and sort keys as specified in the schema.
> 
> ### Schema
> plugin_name - range key (name of the plugin) type_identifier - sort key
> 
> Field name	Attribute type	Description	Example
> plugin_name	String	Range Key	foo
> type_identifier	String	Sort Key	LATEST:bar/baz, MONTH:202302:bar/baz, TOTAL:bar/baz
> timestamp	Number	Holds value for the latest timestamp in milliseconds.	1678132844
> number_of_commits	Number	Holds value for the number_of_commits. Part of the MONTH record	10
> repo	String	Name of the repository	bar/baz
> last_updated_timestamp	Number	timestamp of when the record was last updated	1678132839
> The timestamp record holds the value for period, when the record of `type=MONTH` and the latest commits's timestamp value when `type=LATEST`
> 
> The new dynamo table should have a prefix. If the environment is dev, the prefix should be the stack name. If the environment is staging or prod, the environment can be the prefix. Pass the prefix to the backend lambda.
> 
> #### IAM permission
> The existing backend lambda should be given permission to perform query and getItem actions on the `github-activity` dynamo table. The data workflow lambda should be given permission to batch write to the `github-activity` table.

Based on how the schema is defined in https://docs.google.com/document/d/1WOYxiFU7YVwugYeZmHUR5ynIz9QwRegAp9TCI5uH3CU/edit#heading=h.ciu7pfe1a22x and https://github.com/chanzuckerberg/napari-hub/pull/911/files,`plugin_name` should be `Sort Key` and `type_identifier` should be `Range Key` right?

**Comment by manasaV3** [comment]
The `plugin_name` would be the hash key and the `type_identifier` would be the range key.

**Comment by klai95** [comment]
PR for this ticket has been created: https://github.com/chanzuckerberg/napari-hub/pull/927
