### ISSUE TITLE
Create maintenance activity ETL workflow

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#922]
Update the data workflow lambda's existing activity ETL.

### Workflow

- Use the `last_updated_timestamp` fetched from the parameter store and `current_timestamp` created in the workflow.
- Query snowflake `imaging.github.commits` for all records inserted with ingestion_timestamp after the `last_updated_timestamp` and until `current_timestamp`
- For all the updated plugins, query snowflake for the maintenance activity at a month-level granularity for the months with new records inserted. 
- Transform the results into dynamo record of type MONTH. Batch write all the records to dynamo.
- Query snowflake `imaging.github.commits` for the total commits for all the plugins with new maintenance activity. 
- Transform the results into dynamo record of type TOTAL. Batch write all the records to dynamo.
-  Query snowflake `imaging.github.commits` for the latest commit for all the plugins with new maintenance activity. 
- Transform the results into dynamo record of type LATEST. Batch write all the records to dynamo.

### Schema

plugin_name - range key (name of the plugin)
type_identifier - sort key

| Field name  |  Attribute type |  Description |  Example |
| ----------- | ----------- | ----------- | ----------- |
| plugin_name      | String  | Hash Key |  foo
| type_identifier   | String  | Range Key |  LATEST:bar/baz, MONTH:202302:bar/baz, TOTAL:bar/baz
| timestamp | Number | Holds value for the latest timestamp in milliseconds.  |  1678132844
| number_of_commits | Number | Holds value for the number_of_commits. Part of the MONTH record  |  10
| repo | String | Name of the repository  |  bar/baz
| last_updated_timestamp | Number | timestamp of when the record was last updated | 1678132839

The timestamp record holds the value for period, when the record of `type=MONTH` and the latest commits's timestamp value when `type=LATEST`

The new dynamo table should have a prefix. If the environment is dev, the prefix should be the stack name. If the environment is staging or prod, the environment can be the prefix. Pass the prefix to the backend lambda.

### Logging

Some of data that could be useful to have logged:
- Time taken for each snowflake query
- Time taken for dynamo writes
- Number of records in each batch write
- Exceptions encountered

**Comment by manasaV3** [comment]
Similar to #853

**Comment by klai95** [comment]
Similar to https://github.com/chanzuckerberg/napari-hub/pull/926

**Comment by klai95** [comment]
Pull request for this ticket: https://github.com/chanzuckerberg/napari-hub/pull/939
