### ISSUE TITLE
Update metric API maintenance to use dynamoDB

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#923]
If the incoming request is in the test, fetch the data for `maintenance ` from dynamo else, fetch the results from s3.

### maintenance.timeline

- Query for records from `github-activity` with key condition expression `name=:plugin_name AND type_identifier BETWEEN :start_month AND :end_date` and projection of installs and timestamp field.
```
aws dynamodb query \
--table-name dev-test-github-activity \
--key-condition-expression 'name = :plugin_name AND type_identifier BETWEEN :start_date AND :end_month' \
--expression-attribute-values '{
":plugin_name": {"S": "foo"},
":start_month": {"S": "MONTH:202202"},
":end_month": {"S": "MONTH:202301"},
}'
--projection 'number_of_commits, timestamp'
```
In the above query, replace table_name with the correct table name by stage and stack name. Also, update the expression attribute value to have relevant values for all the fields. The `start_month` and `end_month` should be computed dynamically based on the current date.

- Then, transform the results from the dynamo to the expected format while adding records with a default value for installs for the missing months.

### maintenance.stats.latest_commit_timestamp

- Query for records from `github-activity` with key condition expression `name=:plugin_name AND type_identifier BEGINS_WITH :type` and projection of timestamp field.
```
aws dynamodb query \
--table-name dev-test-github-activity \
--key-condition-expression 'name = :plugin_name AND type_timestamp BEGINS_WITH :type' \
--expression-attribute-values '{
":plugin_name": {"S": "foo"},
":type": {"S": "LATEST:"}
}'
--projection 'timestamp'
```
In the above query, replace table_name with the correct table name by stage and stack name. Also, update the expression attribute value to have relevant values for the plugin_name field. 

- Then, transform the results from the dynamo to the expected format with a fallback to `None` if there are no records.

### maintenance.stats.total_commits

- Query for records from `github-activity` with key condition expression `name=:plugin_name AND type_identifier BEGINS_WITH :type` and projection of timestamp field.
```
aws dynamodb query \
--table-name dev-test-github-activity \
--key-condition-expression 'name = :plugin_name AND type_timestamp BEGINS_WITH :type' \
--expression-attribute-values '{
":plugin_name": {"S": "foo"},
":type": {"S": "TOTAL:"}
}'
--projection 'number_of_commits'
```
In the above query, replace table_name with the correct table name by stage and stack name. Also, update the expression attribute value to have relevant values for the plugin_name field. 

- If the result has a record, populate `total_commits` with the results from the records of type `TOTAL:`. Else set `total_commits` to `0`.

In the above query, replace `foo` with the relevant plugin_name and table_name with the correct prefix. 

**Some of the data that could be useful to have logged:**

- Time taken for dynamo read
- If plugin has query results

### post-merge & post-release to-dos
- Enable the feature flags in the appropriate environments
- Ensure there are no relevant errors on Datadog, Lambda, etc
- Verify the API endpoints work as expected in the appropriate environments
- Verify the plugin page, and any other pages that may be relevant, load as expected
- In this specific case, it requires us to backfill data (reset timestamp to 0) in parameter store so that the tables populate with the appropriate data; it is important to note that the specific steps may differ with each ticket
- This process would be executed for staging (post-merge) and for production (post-release)

**Comment by manasaV3** [comment]
Similar to #854 #855 #856

**Comment by richaagarwal** [comment]
@manasaV3 Sorry, I missed your question earlier.  How does this behave currently?

**Comment by manasaV3** [comment]
> @manasaV3 Sorry, I missed your question earlier. How does this behave currently?

@richaagarwal It only returns the metrics on the repo currently associated to the plugin.

**Comment by richaagarwal** [comment]
> In cases where we have the repository updated for a specific plugin. Should the total_commits surfaced be a summation of the commits across both the repository or just the commits on the latest one? @neuromusic @richaagarwal

For posterity, this was discussed by the napari hub team on 5/15 and we have decided to maintain current behavior: only include the commits for the repository currently associated with the plugin.

**Comment by richaagarwal** [comment]
Let's be sure to enable the feature flag in production once this is deployed next week
