### ISSUE TITLE
Feature flags not fetched for Markdown pages

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#931]
Fetching feature flags for the markdown pages was not implemented in #691, so there's currently a bug where loading a Markdown page initially will show a different UI on the app bar:

https://user-images.githubusercontent.com/2176050/223856903-2cf3ad49-60a3-42d0-8d96-d0ca840de7fc.mp4

Historically we've compiled the Markdown pages to static HTML for performance, but now that different parts of the UI require fetching feature flags, we'll need to convert the Markdown pages to use SSR so we can inject the feature flags at render time.

**Comment by richaagarwal** [comment]
@codemonkey800 Thinking about this one more, I wonder if it may be time to do some feature flags clean-up for older features like Collections?

**Comment by richaagarwal** [comment]
I'm going to close this as we're planning to clean up feature flags for the foreseeable future. @codemonkey800 Let me know if you still think this is something that'd be needed after the clean-up is done.
