### ISSUE TITLE
Improve font sizes for collection page

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#932]
Lighthouse reports that the collection pages are using font sizes that are too small, resulting in a lower SEO score.

## /collections

<img width="513" alt="image" src="https://user-images.githubusercontent.com/2176050/223857341-eb14e992-eee2-4352-b478-f2f902b8f0d0.png">

## /collections/\<symbol\>

<img width="518" alt="image" src="https://user-images.githubusercontent.com/2176050/223864332-94e1d3ee-0aa0-46b3-97f8-93fd1ecb546f.png">

**Comment by Janeece** [comment]
@codemonkey800 Here's the design recommendation we reviewed today: https://www.figma.com/file/UuSPthD5LmDWhCCXRr2O2d/Hub-SEO---Typography-Size?node-id=8%3A941&t=dwPacaw1TcmxEsNc-1

**Comment by Janeece** [comment]
@codemonkey800 just flagging that i previously missed including a type size in my recommendation. Added info for updating Site Title Narrow type size to the design file (linked in my previous comment).
