### ISSUE TITLE
Respond with 404 for plugins that return empty data

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#947]
There's an issue on the frontend and backend right now where calling the API with a plugin is not indexed will return empty data. We should update both the frontend to display a 404 page, and the backend to respond with a 404 status code if the plugin object is empty

## Backend

<img width="490" alt="image" src="https://user-images.githubusercontent.com/2176050/225749063-52c49431-4bac-4d42-8ccc-9c92312a38a1.png">

## Frontend

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2176050/225749117-4f737689-d8ac-467d-bc7a-c8c6f13b99a3.png">

**Comment by richaagarwal** [comment]
I've taken care of the backend portion in https://github.com/chanzuckerberg/napari-hub/pull/1226

@codemonkey800 Updating the current 404 page seems less critical, it's basic but I think it does the job? Let me know if you still think frontend work is needed for this.
