### ISSUE TITLE
Update /plugins API to use dynamoDB

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#949]
### Description

The API should return only public plugins
e.g. visibility == 'public' and is_blocked == False

### Implementation

-  If the incoming request is in the test, fetch the data from dynamoDb or else fetch the results from s3.

- Scan the for records from the `plugin` table on the index on `is_latest` with filter `visibility=public and is_blocked does not exist` and pagination to ensure that all the results have been fetched. 

```
aws dynamodb scan \
--table-name dev-test-plugin \
--index-name dev-test-plugin_name-is_latest \
--filter 'visibility=:visibility and attribute_not_exists(is_blocked)' \
--projection-expression 'formatted_name, version, release_date' \
--expression-attribute-values '{
  ":visibility": {"S": "public"}
}'
```
In the above client call, replace table-name and index-name with the correct table name by stage and stack name.  
This can be implemented in the backend using a scan from boto3 linked [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.scan).

[Link to pynamo resource](https://pynamodb.readthedocs.io/en/stable/batch.html?#scan-filters)  for the same.

- When constructing the response, use the `formatted_name` as the key  and the `version` as value in the JSON
- If there are two entries for a plugin, use the one with the latest `release_date`

### Data to be Logged

- Time taken for dynamo scan and transform
- Total number of results returned

**Comment by richaagarwal** [comment]
Removing this from our backlog as we will not need to migrate this over at this time
