### ISSUE TITLE
Update /plugins/index API to use dynamoDB

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#950]
### Description

The API should return only public plugins metadata as a list
e.g. visibility == 'public' and is_blocked == False

### Implementation

-  If the incoming request is in the test, fetch the data from dynamoDb or else fetch the results from s3.

- Scan the for records from the `plugin` table on the index on `is_latest` with filter `visibility=public and is_blocked does not exist` and pagination to ensure that all the results have been fetched. 

```
aws dynamodb scan \
--table-name dev-test-plugin \
--index-name dev-test-plugin_name-is_latest \
--filter 'visibility=:visibility and attribute_not_exists(is_blocked)' \
--projection-expression 'data, release_date' \
--expression-attribute-values '{
  ":visibility": {"S": "public"}
}'
```

In the above client call, replace table-name and index-name with the correct table name by stage and stack name.  
This can be implemented in the backend using a scan from boto3 linked [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.scan).

[Link to pynamo resource](https://pynamodb.readthedocs.io/en/stable/batch.html?#scan-filters)  for the same.

- When constructing the response use the data field, and retain only the following fields from the data: 
```
'name', 'summary', 'description_text', 'description_content_type', 'authors', 'license', 'python_version', 'operating_system',
'release_date', 'version', 'first_released', 'development_status', 'category', 'display_name', 'plugin_types', 'reader_file_extensions',
'writer_file_extensions', 'writer_save_layers', 'npe2', 'error_message', 'code_repository'
```
- If there are two entries for a plugin, use the record with the latest `release_date`

### Data to be Logged

- Time taken for dynamo scan and transform
- Total number of results returned

**Comment by richaagarwal** [comment]
We need to put a little more thought into this one before beginning implementation - we may want to secure this with an API key or consider alternatives to it once we introduce a search API.  I'll label this blocked for now

**Comment by richaagarwal** [comment]
Following up on the above comment, we should secure this with an API key. If an API key is not provided, an error message should be returned.  TBD on the exact contents of the error message, but that shouldn't block work on this ticket for now.

**Comment by manasaV3** [comment]
Also add functionality from: https://github.com/chanzuckerberg/napari-hub/issues/993
