### ISSUE TITLE
Update /plugins/excluded API to use dynamoDB

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#951]
### Description

The API should return non-public plugins
e.g. visibility != 'public'

### Implementation

- Scan the for records from the `plugin` table on the index on `is_latest` with filter `visibility=public and is_blocked does not exist` and pagination to ensure that all the results have been fetched. 

```
aws dynamodb scan \
--table-name dev-test-plugin \
--index-name dev-test-plugin_name-is_latest
--filter 'visibility<>:visibility' \
--projection-expression 'formatted_name, visibility'
--expression-attribute-values '{
  ":visibility": {"S": "public"}
}'
```

```
aws dynamodb scan \
--table-name dev-test-plugin-excluded \
--filter 'visibility<>:visibility' \
--projection-expression 'formatted_name, visibility'
```

Merge the results from both the queries

In the above client call, replace table-name and index-name with the correct table name by stage and stack name.  
This can be implemented in the backend using a scan from boto3 linked [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.scan).

[Link to pynamo resource](https://pynamodb.readthedocs.io/en/stable/batch.html?#scan-filters)  for the same.

- When constructing the response, use the `formatted_name` as the key in the JSON
- If there are two entries for a plugin, use the one with the latest `last_updated_timestamp`

### Data to be Logged

- Time taken for dynamo scans and transform
- Total number of results returned

**Comment by manasaV3** [comment]
Check with @richaagarwal before implementing to ensure this still needs to be supported.

**Comment by richaagarwal** [comment]
Removing this from our backlog as we will not need to migrate this over at this time
