### ISSUE TITLE
Update /manifest API endpoints to use dynamoDB

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#952]
### Description

The API should only return plugin manifest data if it has public or hidden visibility and is not blocked.
e.g. visibility IN ('public', 'hidden') and is_blocked == False

### Implementation

- If the incoming request is in the test, fetch the data from dynamoDb or else fetch the results from s3.

#### If the version is specified in the request:

- Convert the plugin_name to lowercase, and use it as the hash_key.

- Add the sort key to the key condition by appending `:aggregate` to the `version` and query the `plugin` table with additional filters `visibility='public' or 'hidden' and is_blocked does not exist`.

```
aws dynamodb query \
--table-name dev-test-plugin \
--key-conditions 'name=:plugin_name AND version_type = :version_type)' \
--filter-conditions 'visibility IN ('public', 'hidden)  AND attribute_not_exists(is_blocked)'
--projection-expression 'version, release_date' \
--expression-attribute-values '{
":plugin_name": {"S": "foo"},
":version_type": {"S": "1.0.0:aggregate"},
}'
```

#### If the version is not specified in the request:

- Convert the plugin_name to lowercase, and use it as the hash_key.

- Query on the index created on `is_latest` field with additional filters `visibility='public' or 'hidden' and is_blocked does not exist`.

```
aws dynamodb query \
--table-name dev-test-plugin \
--index-name: dev-test-plugin_name-is_latest
--key-conditions 'name=:plugin_name' \
--filter-conditions 'visibility IN ('public', 'hidden) AND attribute_not_exists(is_blocked)' \
--projection-expression 'version, release_date' \
--expression-attribute-values '{
":plugin_name": {"S": "foo"}
}'
```
#### Processing for the version

- If the above query has no result, the API should return `{}` as the response.
- If multiple records are returned, use the one with the latest release_date to get the version

### Getting the manifest data:
- Get from the plugin table with the key condition name is plugin_name and version_type equal to the value created by appending `:distribution` to the version identified in the previous step. 

```
aws dynamodb getItem \
--table-name dev-test-plugin \
--key-conditions 'name=:plugin_name AND version_type = :version_type)' \
--expression-attribute-values '{
":plugin_name": {"S": "foo"},
":version_type": {"S": "1.0.0:distribution"},
}'
```
#### Processing the result from GetItem 

```

if get has no result:
  return {'error': 'Manifest not yet processed.'}
else:
    get "data" attribute from result

    if data == {}:
        return {'error': 'Processing manifest failed due to external error.'}

    if data has attribute 'error':        
        return {'error': plugin_metadata['error']}

    return data
```

### Data to be Logged
- Time taken for dynamo query, getItem
- In case of errors encountered in the manifest data.

**Comment by manasaV3** [comment]
Check with @richaagarwal before implementation to verify if this endpoint needs to be supported.

**Comment by richaagarwal** [comment]
Removing this from our backlog as we will not need to migrate this over at this time
