### ISSUE TITLE
add PartSeg to exclusion list b/c not a napari plugin?

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#99]
can we add "PartSeg" to the exclusion list? even though it has the "Framework :: napari" trove classifier, it isn't a napari plugin

in the future, we should consider automatically excluding packages that have the trove classifier but don't have hook implementations, but until then, we can manually clean up the listings for users.

cc @Czaki

**Comment by Czaki** [comment]
PartSeg is both. Standalone program and set of napari plugins. I have a few branches which are in the progress of wrapping part of PartSeg utilities into napari plugins.

**Comment by neuromusic** [comment]
gotcha. if PartSeg is installed into an existing napari environment (say, through the "install plugin menu"), are those plugins then available to users?

**Comment by Czaki** [comment]
Almost all. Only plugin for synchronization state from PartSeg instance to napari instance is exclusive for invoking napari viewer from PartSeg menu.

**Comment by neuromusic** [comment]
ok, sounds good. cc @ziyangczi
