### ISSUE TITLE
No commit data shown on napari hub for hidden plugins

### ISSUE THREAD

**Issue by klai95** [chanzuckerberg/napari-hub#998]
`Problem`:
Currently, there are plugins we are not showing commit data even though we have Snowflake data for them. The reason for this behavior is as follows:

Since we only have access to repo values in `latest_commit` and `commit_activity` SQL queries, we needed to created repo to plugin mappings so that latest_commit.json and commit_activity.json can store data with respect to plugins instead of repos.
However, such mappings are only available for public plugins, or in other words, plugins that exist in index.json, and this is the reason why hidden plugins (such as `napari-threedee`), which do not exist in `index.json`, did not have commit data.

`References`: Please check out https://www.napari-hub.org/plugins/napari-threedee and click on the Activity tab and view the Maintenance section, and see the commits at https://github.com/napari-threedee/napari-threedee.

**Comment by richaagarwal** [comment]
cc @neuromusic - wanted you to be aware of this issue, but my feeling is it's not critical to address given it only impacts hidden plugins.

**Comment by richaagarwal** [comment]
Looks like this has been fixed as part of the migration work. Closing
